name = "compliance-iegm-dashboard"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "compliance-iegm-dashboard-db"
database_id = "5803f64b-c4f9-434d-b279-abb8d8f57e5f"
migrations_dir = "src/db/migrations"

# D1 binding will be managed by Terraform/Wrangler
[[kv_namespaces]]
binding = "KV_SIMULADOS"
id = "d6763c9e5c58401784d7ee60cc28d463"
