-- Atualização de textos para remover ambiguidades/repetições
-- Fonte: scripts/i-Educ.JSON

UPDATE questoes SET texto = 'Realiza higienização dos brinquedos/materiais pedagógicos? (Creche)' WHERE chave_questao = 'M01Q06441';
UPDATE questoes SET texto = 'Qual a frequência de higienização? (Creche)' WHERE chave_questao = 'M01Q06442';
UPDATE questoes SET texto = 'Possui cronograma para compra de brinquedos/materiais pedagógicos? (Creche)' WHERE chave_questao = 'M01Q06443';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Creche)' WHERE chave_questao = 'M01Q06484R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Creche)' WHERE chave_questao = 'M01Q06486R00100';
UPDATE questoes SET texto = 'Realiza higienização dos brinquedos/materiais pedagógicos? (Pré-escola)' WHERE chave_questao = 'M01Q06531';
UPDATE questoes SET texto = 'Qual a frequência de higienização? (Pré-escola)' WHERE chave_questao = 'M01Q06532';
UPDATE questoes SET texto = 'Possui cronograma para compra de brinquedos/materiais pedagógicos? (Pré-escola)' WHERE chave_questao = 'M01Q06533';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Pré-escola)' WHERE chave_questao = 'M01Q06584R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Pré-escola)' WHERE chave_questao = 'M01Q06586R00100';
UPDATE questoes SET texto = 'O Município possui, no planejamento, ações governamentais para enfrentamento ao bullying? (Anos Iniciais)' WHERE chave_questao = 'M01Q07500';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Iniciais)' WHERE chave_questao = 'M01Q07610R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Iniciais)' WHERE chave_questao = 'M01Q07710R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Iniciais)' WHERE chave_questao = 'M01Q07810R00100';
UPDATE questoes SET texto = 'O Município possui seu próprio indicador de qualidade de ensino? (Anos Iniciais)' WHERE chave_questao = 'M01Q07900';
UPDATE questoes SET texto = 'Especifique, descrevendo sua composição e forma de avaliação: (Anos Iniciais)' WHERE chave_questao = 'M01Q07910R00100';
UPDATE questoes SET texto = 'O indicador próprio de qualidade de ensino do Município classifica os alunos por nível de desempenho? (Anos Iniciais)' WHERE chave_questao = 'M01Q07920';
UPDATE questoes SET texto = 'Especifique como são classificados os alunos por nível de desempenho: (Anos Iniciais)' WHERE chave_questao = 'M01Q07921R00100';
UPDATE questoes SET texto = 'O indicador próprio de qualidade de ensino do Município possui metas específicas? (Anos Iniciais)' WHERE chave_questao = 'M01Q07930';
UPDATE questoes SET texto = 'É possível avaliar a quantidade de participantes da última edição da avaliação municipal própria? (Anos Iniciais)' WHERE chave_questao = 'M01Q07940';
UPDATE questoes SET texto = 'Existem metas traçadas que visem à melhoria dos resultados dos projetos de recuperação ou reforço escolar? (Anos Iniciais)' WHERE chave_questao = 'M01Q03330';
UPDATE questoes SET texto = 'As metas estão sendo atingidas? (Anos Iniciais)' WHERE chave_questao = 'M01Q03311';
UPDATE questoes SET texto = 'A Prefeitura municipal realizou ações e medidas para monitoramento da taxa de abandono das crianças na idade escolar (Anos Iniciais)?' WHERE chave_questao = 'M01Q00100';
UPDATE questoes SET texto = 'Assinale as ações e medidas realizadas: (Anos Iniciais)' WHERE chave_questao = 'M01Q00130';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Dificuldade de acesso à escola: (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00100';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Desinteresse: (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00200';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Necessidade de trabalhar: (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00300';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Falta de infraestrutura escolar: (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00500';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Bullying: (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00600';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Outros (Anos Iniciais)' WHERE chave_questao = 'M01Q00120R00400';
UPDATE questoes SET texto = 'O Município possui, no planejamento, ações governamentais para enfrentamento ao bullying? (Anos Finais)' WHERE chave_questao = 'M01Q09600';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Finais)' WHERE chave_questao = 'M01Q09710R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Finais)' WHERE chave_questao = 'M01Q09810R00100';
UPDATE questoes SET texto = 'Informe a data da última entrega na escola: (Anos Finais)' WHERE chave_questao = 'M01Q09910R00100';
UPDATE questoes SET texto = 'O Município possui seu próprio indicador de qualidade de ensino? (Anos Finais)' WHERE chave_questao = 'M01Q10000';
UPDATE questoes SET texto = 'Especifique, descrevendo sua composição e forma de avaliação: (Anos Finais)' WHERE chave_questao = 'M01Q10010R00100';
UPDATE questoes SET texto = 'O indicador próprio de qualidade de ensino do Município classifica os alunos por nível de desempenho? (Anos Finais)' WHERE chave_questao = 'M01Q10020';
UPDATE questoes SET texto = 'Especifique como são classificados os alunos por nível de desempenho: (Anos Finais)' WHERE chave_questao = 'M01Q10021R00100';
UPDATE questoes SET texto = 'O indicador próprio de qualidade de ensino do Município possui metas específicas? (Anos Finais)' WHERE chave_questao = 'M01Q10030';
UPDATE questoes SET texto = 'É possível avaliar a quantidade de participantes da última edição da avaliação municipal própria? (Anos Finais)' WHERE chave_questao = 'M01Q10040';
UPDATE questoes SET texto = 'Existem metas traçadas que visem à melhoria dos resultados dos projetos de recuperação ou reforço escolar? (Anos Finais)' WHERE chave_questao = 'M01Q10920';
UPDATE questoes SET texto = 'As metas estão sendo atingidas? (Anos Finais)' WHERE chave_questao = 'M01Q10921';
UPDATE questoes SET texto = 'A Prefeitura municipal realizou ações e medidas para monitoramento da taxa de abandono das crianças na idade escolar (Anos Finais)?' WHERE chave_questao = 'M01Q11200';
UPDATE questoes SET texto = 'Assinale as ações e medidas realizadas: (Anos Finais)' WHERE chave_questao = 'M01Q11210';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Dificuldade de acesso à escola: (Anos Finais)' WHERE chave_questao = 'M01Q11220R00100';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Desinteresse: (Anos Finais)' WHERE chave_questao = 'M01Q11220R00200';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Necessidade de trabalhar: (Anos Finais)' WHERE chave_questao = 'M01Q11220R00300';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Falta de infraestrutura escolar: (Anos Finais)' WHERE chave_questao = 'M01Q11220R00500';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Bullying: (Anos Finais)' WHERE chave_questao = 'M01Q11220R00600';
UPDATE questoes SET texto = 'Informe a quantidade de crianças que abandonaram a escola pelos seguintes motivos: Outros (Anos Finais)' WHERE chave_questao = 'M01Q11220R00400';
