-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Fiscal.JSON
-- Indicador: i-Fiscal

UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00352';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00310R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00310R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00310R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00331';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00333';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00335R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00350';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":5},{"texto":"Não","valor":0},{"texto":"Não possui sistema (software) para lançamento, arrecadação ou fiscalização dos tributos","valor":-3}]' WHERE chave_questao = 'M04Q00351';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M03Q03100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00400';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Recadastramento de Imóveis","valor":0},{"texto":"Programas de Recuperação Fiscal","valor":0},{"texto":"Implementação de Nota Fiscal Eletrônica","valor":0},{"texto":"Convênios com a União e o Estado para compartilhamento de Informações","valor":0},{"texto":"Parceria/Convênio com os tabelionatos de notas e Registros de Imóveis","valor":0},{"texto":"Protesto da Certidão de Dívida Ativa","valor":0},{"texto":"Convênios com órgãos de proteção ao crédito","valor":0},{"texto":"Convênio com o Governo Federal para a cobrança do ITR","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M04Q00420';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q10200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q10201R00200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Menor ou igual a 1 ano","valor":0},{"texto":"Maior que 1 e menor ou igual a 4 anos","valor":0},{"texto":"Maior que 4 e menor ou igual a 8 anos","valor":0},{"texto":"Maior que 8 anos","valor":0}]' WHERE chave_questao = 'M04Q00600';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q10202';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00521R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00510';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, de forma automática no sistema","valor":6},{"texto":"Sim, de forma manual","valor":2},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M04Q00550';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Alíquotas diferenciadas em razão da localização do imóvel","valor":50},{"texto":"Outros","valor":0},{"texto":"Não há diferenciação nas alíquotas dos imóveis","valor":-1},{"texto":"Alíquotas progressivas em razão do valor do imóvel","valor":1},{"texto":"Alíquotas diferenciadas em razão do uso do imóvel","valor":0.5}]' WHERE chave_questao = 'M04Q10300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q00821R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q10400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q10401';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim por meio de sistema automatizado","valor":15},{"texto":"Sim, manualmente","valor":8},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M04Q01000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, sem restrição","valor":0},{"texto":"Sim, com restrição (Ex.: há necessidade de cadastro para acessar o resultado da pesquisa)","valor":-9},{"texto":"Serviço não disponibilizado","valor":-15},{"texto":"Não implantou a NFS-e","valor":-15}]' WHERE chave_questao = 'M04Q01010';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q02211R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02252';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q01100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q01400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q01430R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02350';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q10500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02420';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q02422R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as renúncias concedidas estão contidas no demonstrativo","valor":0},{"texto":"A maior parte das renúncias concedidas estão contidas no demonstrativo","valor":-1},{"texto":"A menor parte das renúncias concedidas estão contidas no demonstrativo","valor":-3},{"texto":"Não há demonstrativo","valor":-5}]' WHERE chave_questao = 'M04Q01210';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q01211';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02440';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q02445R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q02511R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Cobrança administrativa da dívida ativa","valor":1.5},{"texto":"Parcelamento da dívida ativa","valor":1.5},{"texto":"Restrição e controle da inadimplência nos parcelamentos da dívida ativa","valor":1.5},{"texto":"Início do trâmite da execução judicial da dívida ativa","valor":1.5},{"texto":"Anistia","valor":1.5},{"texto":"Remissão","valor":1.5}]' WHERE chave_questao = 'M04Q02540';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não houve prescrição","valor":0}]' WHERE chave_questao = 'M04Q02800';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02830';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, de todas as ações","valor":0},{"texto":"Sim, da maior parte das ações","valor":-1},{"texto":"Sim, da menor parte das ações","valor":-3},{"texto":"Não","valor":-5}]' WHERE chave_questao = 'M04Q03500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"PPA, LDO e LOA","valor":2.5},{"texto":"Balanços de exercício","valor":2.5},{"texto":"Prestação de contas do ano anterior","valor":2.5},{"texto":"Parecer prévio do TC","valor":2.5},{"texto":"Relatório de Gestão Fiscal (RGF)","valor":2.5},{"texto":"Relatório Resumido da Execução Orçamentária (RREO)","valor":2.5}]' WHERE chave_questao = 'M07Q00920';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q03000';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q03100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q03110R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q03200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todos os repasses foram dentro do prazo legal","valor":0},{"texto":"A maior parte dos repasses recolhidos até 30 dias após o vencimento","valor":-4},{"texto":"A maior parte dos repasses recolhidos de 31 a 90 dias do vencimento","valor":-15},{"texto":"A maior parte dos repasses recolhidos acima de 90 dias do vencimento","valor":-21},{"texto":"Os repasses não foram realizados","valor":-30}]' WHERE chave_questao = 'M04Q03300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q03400';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as parcelas foram recolhidas dentro do prazo legal","valor":0},{"texto":"A maior parte das parcelas recolhidas até 30 dias após o vencimento","valor":-4},{"texto":"A maior parte das parcelas recolhidas de 31 a 90 dias do vencimento","valor":-15},{"texto":"A maior parte das parcelas recolhidas acima de 90 dias do vencimento","valor":-21},{"texto":"As parcelas não foram recolhidas","valor":-30}]' WHERE chave_questao = 'M04Q03410';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q01900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Encaminhou no prazo","valor":50},{"texto":"Encaminhou fora do prazo","valor":25},{"texto":"Não encaminhou","valor":0}]' WHERE chave_questao = 'M04Q09000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Menor ou igual a 20","valor":25},{"texto":"Maior que 20 e menor que 41","valor":10},{"texto":"Maior ou igual a 41","valor":0}]' WHERE chave_questao = 'M04Q09300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Menor ou igual a 1","valor":25},{"texto":"Maior que 1 e menor que 18","valor":10},{"texto":"Maior ou igual a 18","valor":0}]' WHERE chave_questao = 'M04Q09400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q08205R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q09100R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q09100R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q09200R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q09700R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M04Q02000';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M04Q02010R00100';
-- Respostas de referência Betim 2025 — i-Fiscal TCEMG-2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00300';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q10200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00500';
UPDATE questoes SET resposta_ref = '["Alíquotas progressivas em razão do valor do imóvel","Alíquotas diferenciadas em razão do uso do imóvel"]' WHERE chave_questao = 'M04Q10300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q10400';
UPDATE questoes SET resposta_ref = 'Sim por meio de sistema automatizado' WHERE chave_questao = 'M04Q01000';
UPDATE questoes SET resposta_ref = 'Sim, sem restrição' WHERE chave_questao = 'M04Q01010';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q01400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q10500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02800';
UPDATE questoes SET resposta_ref = 'Sim, da maior parte das ações' WHERE chave_questao = 'M04Q03500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00900';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q02900';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q03000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q03100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q03200';
UPDATE questoes SET resposta_ref = 'Todos os repasses foram dentro do prazo legal' WHERE chave_questao = 'M04Q03300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q03400';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q01900';
UPDATE questoes SET resposta_ref = 'Encaminhou no prazo' WHERE chave_questao = 'M04Q09000';
UPDATE questoes SET resposta_ref = 'Menor ou igual a 20' WHERE chave_questao = 'M04Q09300';
UPDATE questoes SET resposta_ref = 'Menor ou igual a 1' WHERE chave_questao = 'M04Q09400';
UPDATE questoes SET resposta_ref = '193 989 399,6100' WHERE chave_questao = 'M04Q08205R00100';
UPDATE questoes SET resposta_ref = '582 102 190,5300' WHERE chave_questao = 'M04Q09100R00100';
UPDATE questoes SET resposta_ref = '28 316 358,1800' WHERE chave_questao = 'M04Q09100R00200';
UPDATE questoes SET resposta_ref = '16 112 354,0000' WHERE chave_questao = 'M04Q09200R00100';
UPDATE questoes SET resposta_ref = '0,0000' WHERE chave_questao = 'M04Q09700R00300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00352';
UPDATE questoes SET resposta_ref = '17' WHERE chave_questao = 'M04Q00310R00100';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M04Q00310R00300';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M04Q00310R00200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00331';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00333';
UPDATE questoes SET resposta_ref = 'https://legislativo.camarabetim.mg.gov.br/NormaJuridica/ShowNormaJuridica/31442' WHERE chave_questao = 'M04Q00335R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q00350';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q00351';
UPDATE questoes SET resposta_ref = '["Convênios com a União e o Estado para compartilhamento de Informações"]' WHERE chave_questao = 'M04Q00420';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/portal/diario-oficial/ver/3126 (página 10 a 20)' WHERE chave_questao = 'M04Q10201R00200';
UPDATE questoes SET resposta_ref = 'Menor ou igual a 1 ano' WHERE chave_questao = 'M04Q00600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q10202';
UPDATE questoes SET resposta_ref = '(Página 22 a 60) https://www.betim.mg.gov.br/uploads/diario_20241331163939d0079d7c6687c7c4670833bedb9870.pdf' WHERE chave_questao = 'M04Q00521R00100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q00510';
UPDATE questoes SET resposta_ref = 'Sim, de forma automática no sistema' WHERE chave_questao = 'M04Q00550';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/uploads/diario_202517181610f801bfa51a2f4ff3ffcda33132db0f91.pdf (Página 7 a 79)' WHERE chave_questao = 'M04Q00821R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q10401';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/uploads/diario_20241331163939d0079d7c6687c7c4670833bedb9870.pdf' WHERE chave_questao = 'M04Q02211R00100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q02252';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q01100';
UPDATE questoes SET resposta_ref = '=1' WHERE chave_questao = 'M04Q01430R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02350';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02420';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/renuncias-receitas/renuncias-receitas' WHERE chave_questao = 'M04Q02422R00100';
UPDATE questoes SET resposta_ref = 'Todas as renúncias concedidas estão contidas no demonstrativo' WHERE chave_questao = 'M04Q01210';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q01211';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M04Q02440';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/renuncias-receitas/renuncias-receitas' WHERE chave_questao = 'M04Q02445R00100';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/publicos/63fa1b6a58b4cd6790248215c38a02da.pdf' WHERE chave_questao = 'M04Q02511R00100';
UPDATE questoes SET resposta_ref = '["Cobrança administrativa da dívida ativa","Parcelamento da dívida ativa","Restrição e controle da inadimplência nos parcelamentos da dívida ativa","Início do trâmite da execução judicial da dívida ativa","Anistia"]' WHERE chave_questao = 'M04Q02540';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M04Q02830';
UPDATE questoes SET resposta_ref = '["PPA, LDO e LOA","Relatório Resumido da Execução Orçamentária (RREO)"]' WHERE chave_questao = 'M07Q00920';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/gestao-pessoas' WHERE chave_questao = 'M04Q03110R00100';
UPDATE questoes SET resposta_ref = 'Todas as parcelas foram recolhidas dentro do prazo legal' WHERE chave_questao = 'M04Q03410';
UPDATE questoes SET resposta_ref = 'INFORMAMOS QUE DADOS REFERENTE A VALORES DE DEVIDA ATIVA FORAM PREENCHIDOS COM VALOR ZERO DEVIDO A AUSÊNCIA DAS INFORMAÇÕES DA PARTE DO SISTEMA OPERACIONAL. OS DADOS FORAM SOLICITADOS POREM NÃO HOUVE RETORNO EM TEMPO HÁBIL UMA VEZ QUE A DATA LIMITE PARA PREENCHIMENTO DO QUESTIONÁRIO SE ENCERRA HOJE. APÓS ANÁLISE AS INFORMAÇÕES NO MANUAL DE UTILIZAÇÃO IEGM EXISTE A POSSIBILIDADE DE ALTERAÇÃO VIA SOLICITAÇÃO JUNTO AO SEU RESPECTIVO TRIBUNAL A DEVIDA PERMISSÃO, NA QUAL UTILIZAREMOS A FERRAMENTA ASSIM QUE HOUVER RETORNO DOS VALORES.' WHERE chave_questao = 'M04Q02010R00100';
