-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Gov-Ti.JSON
-- Indicador: i-Gov

UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q00310R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q00310R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q00310R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q00310R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00500';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Outros","valor":0},{"texto":"Gestão e Segurança","valor":0},{"texto":"Análise de Dados","valor":0},{"texto":"Desenvolvimento e Software","valor":0},{"texto":"Infraestrutura e Redes","valor":0}]' WHERE chave_questao = 'M07Q00520';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Há participação do pessoal de TI no processo de compra (especificação técnica, comissão de julgamento, recebimento do objeto)","valor":0},{"texto":"Não há pessoal de TI envolvido no processo de compra","valor":0}]' WHERE chave_questao = 'M07Q01000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Elaboração do edital / especificação técnica","valor":15},{"texto":"Comissão de julgamento","valor":10},{"texto":"Recebimento do objeto","valor":15}]' WHERE chave_questao = 'M07Q01010';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Não foi realizado","valor":0},{"texto":"Sim, para todos os softwares","valor":20},{"texto":"Sim, para a maior parte dos softwares","valor":15},{"texto":"Sim, para a menor parte dos softwares","valor":8},{"texto":"Não foi adquirido nenhum software nos últimos 5 anos","valor":20}]' WHERE chave_questao = 'M07Q01020';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"SIM","valor":0},{"texto":"NÃO POSSUI PDTI","valor":0}]' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"SIM, com metas acima de 02 anos","valor":40},{"texto":"SIM, com metas para até 02 anos","valor":30}]' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00220';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Assinatura eletrônica de uso gratuito","valor":10},{"texto":"Assinatura eletrônica onerosa","valor":0}]' WHERE chave_questao = 'M07Q00222';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03442';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03410';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03420';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03430';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03440';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q01900';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q01911R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q00610R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, para todo o conteúdo do site","valor":20},{"texto":"Sim, para a maior parte do conteúdo do site","valor":10},{"texto":"Sim, para a menor parte do conteúdo do site","valor":5},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M07Q00620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Possibilita para todos os relatórios","valor":20},{"texto":"Possibilita para a maior parte dos relatórios","valor":10},{"texto":"Possibilita para a menor parte dos relatórios","valor":5},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M07Q00630';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q00650';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, para todo o conteúdo do site","valor":30},{"texto":"Sim, para a maior parte do conteúdo do site","valor":15},{"texto":"Sim, para a menor parte do conteúdo do site","valor":5},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M07Q00660';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q02300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q02310';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q02320';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q02330';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03500';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Contabilidade","valor":0},{"texto":"Gestão de tributos (arrecadação)","valor":0},{"texto":"Dívida Ativa","valor":0},{"texto":"Precatórios","valor":0},{"texto":"Gestão patrimonial (bens e equipamentos)","valor":0},{"texto":"Gestão de negócios (Business Intelligence)","valor":0},{"texto":"Planejamento","valor":0},{"texto":"Recursos humanos / Departamento pessoal","valor":0},{"texto":"Almoxarifado","valor":0},{"texto":"Controle de frotas","valor":0},{"texto":"Controle Interno","valor":0},{"texto":"Saúde","valor":0},{"texto":"Ensino (educação)","valor":0},{"texto":"Compras, licitações e contratos","valor":0},{"texto":"Certidões e alvarás","valor":0},{"texto":"Saneamento","valor":0},{"texto":"Cemitérios","valor":0}]' WHERE chave_questao = 'M07Q03510';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Gestão de tributos (arrecadação)","valor":0},{"texto":"Dívida Ativa","valor":0},{"texto":"Precatórios","valor":0},{"texto":"Gestão patrimonial (bens e equipamentos)","valor":0},{"texto":"Gestão de negócios (Business Intelligence)","valor":0},{"texto":"Planejamento","valor":0},{"texto":"Recursos humanos / Departamento pessoal","valor":0},{"texto":"Almoxarifado","valor":0},{"texto":"Controle de frotas","valor":0},{"texto":"Controle Interno","valor":0},{"texto":"Saúde","valor":0},{"texto":"Ensino (educação)","valor":0},{"texto":"Compras, licitações e contratos","valor":0},{"texto":"Certidões e alvarás","valor":0},{"texto":"Saneamento","valor":0},{"texto":"Cemitérios","valor":0}]' WHERE chave_questao = 'M07Q03530';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Totalmente integrado (Inscrição / Atualização e Baixa)","valor":50},{"texto":"Somente as Inscrições /Atualizações estão integrados","valor":10},{"texto":"Somente as Baixas estão integradas","valor":10}]' WHERE chave_questao = 'M07Q03531';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Contabilidade","valor":0},{"texto":"Gestão de tributos (arrecadação)","valor":0},{"texto":"Dívida Ativa","valor":0},{"texto":"Precatórios","valor":0},{"texto":"Gestão patrimonial (bens e equipamentos)","valor":0},{"texto":"Gestão de negócios (Business Intelligence)","valor":0},{"texto":"Planejamento","valor":0},{"texto":"Recursos humanos / Departamento pessoal","valor":0},{"texto":"Almoxarifado","valor":0},{"texto":"Controle de frotas","valor":0},{"texto":"Controle Interno","valor":0},{"texto":"Saúde","valor":0},{"texto":"Ensino (educação)","valor":0},{"texto":"Compras, licitações e contratos","valor":0},{"texto":"Certidões e alvarás","valor":0},{"texto":"Saneamento","valor":0},{"texto":"Cemitérios","valor":0}]' WHERE chave_questao = 'M07Q03540';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Contabilidade","valor":0},{"texto":"Gestão de tributos (arrecadação)","valor":0},{"texto":"Dívida Ativa","valor":0},{"texto":"Precatórios","valor":0},{"texto":"Gestão patrimonial (bens e equipamentos)","valor":0},{"texto":"Gestão de negócios (Business Intelligence)","valor":0},{"texto":"Planejamento","valor":0},{"texto":"Recursos humanos / Departamento pessoal","valor":0},{"texto":"Almoxarifado","valor":0},{"texto":"Controle de frotas","valor":0},{"texto":"Controle Interno","valor":0},{"texto":"Saúde","valor":0},{"texto":"Ensino (educação)","valor":0},{"texto":"Compras, licitações e contratos","valor":0},{"texto":"Certidões e alvarás","valor":0},{"texto":"Saneamento","valor":0},{"texto":"Cemitérios","valor":0}]' WHERE chave_questao = 'M07Q03550';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Alvarás/licenças de funcionamento","valor":7.5},{"texto":"Certidões","valor":7.5},{"texto":"Licenças / autorizações","valor":7.5},{"texto":"Ouvidoria","valor":7.5},{"texto":"Consulta de débitos municipais","valor":7.5},{"texto":"Emissão de guias/boletos dos débitos municipais","valor":7.5},{"texto":"Solicitação de serviços de zeladoria","valor":7.5},{"texto":"Solicitação de obras e serviços de urbanização","valor":7.5},{"texto":"Inscrições em oficinas, cursos, eventos e vagas","valor":7.5},{"texto":"Nota fiscal eletrônica","valor":7.5},{"texto":"Canal de denúncias","valor":7.5},{"texto":"Cadastro de fornecedores","valor":7.5},{"texto":"Agendamento de consultas na rede pública de saúde","valor":7.5},{"texto":"Agendamento de exames em relação a doenças crônicas na rede pública de saúde","valor":7.5},{"texto":"Pesquisa de satisfação em relação aos serviços prestados pela Prefeitura","valor":7.5},{"texto":"Consulta a status de protocolos de todos os atendimentos dos serviços assinalados acima","valor":7.5}]' WHERE chave_questao = 'M07Q03610';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Telefone","valor":0},{"texto":"Site da Prefeitura","valor":0},{"texto":"Aplicativo de mensagens","valor":0},{"texto":"Redes sociais","valor":0},{"texto":"Aplicativo da Prefeitura","valor":0},{"texto":"Correio eletrônico (e-mail)","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M07Q03710';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03900';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M07Q03911R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todos os contratos vigentes","valor":0},{"texto":"A maior parte dos contratos vigentes","valor":0},{"texto":"A menor parte dos contratos vigentes","valor":0},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M07Q03920';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q04100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M07Q03000';
-- Respostas de referência Betim 2025 — i-Gov Nacional - 2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03300';
UPDATE questoes SET resposta_ref = 'SIM' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q01900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03900';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q04100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00300';
UPDATE questoes SET resposta_ref = '41' WHERE chave_questao = 'M07Q00310R00100';
UPDATE questoes SET resposta_ref = '4' WHERE chave_questao = 'M07Q00310R00200';
UPDATE questoes SET resposta_ref = '21' WHERE chave_questao = 'M07Q00310R00300';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M07Q00310R00400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00500';
UPDATE questoes SET resposta_ref = '["Infraestrutura e Redes","Desenvolvimento e Software","Análise de Dados","Gestão e Segurança"]' WHERE chave_questao = 'M07Q00520';
UPDATE questoes SET resposta_ref = 'Há participação do pessoal de TI no processo de compra (especificação técnica, comissão de julgamento, recebimento do objeto)' WHERE chave_questao = 'M07Q01000';
UPDATE questoes SET resposta_ref = '["Elaboração do edital / especificação técnica","Comissão de julgamento","Recebimento do objeto"]' WHERE chave_questao = 'M07Q01010';
UPDATE questoes SET resposta_ref = 'Sim, para a maior parte dos softwares' WHERE chave_questao = 'M07Q01020';
UPDATE questoes SET resposta_ref = 'SIM, com metas acima de 02 anos' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00220';
UPDATE questoes SET resposta_ref = 'Assinatura eletrônica onerosa' WHERE chave_questao = 'M07Q00222';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03442';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03410';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03420';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03430';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03440';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/arquivos/atos_21_20170529_284.pdf' WHERE chave_questao = 'M07Q01911R00100';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/' WHERE chave_questao = 'M07Q00610R00100';
UPDATE questoes SET resposta_ref = 'Sim, para todo o conteúdo do site' WHERE chave_questao = 'M07Q00620';
UPDATE questoes SET resposta_ref = 'Possibilita para a maior parte dos relatórios' WHERE chave_questao = 'M07Q00630';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q00650';
UPDATE questoes SET resposta_ref = 'Sim, para todo o conteúdo do site' WHERE chave_questao = 'M07Q00660';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02310';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02320';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q02330';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Gestão de negócios (Business Intelligence)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03510';
UPDATE questoes SET resposta_ref = '["Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03530';
UPDATE questoes SET resposta_ref = 'Totalmente integrado (Inscrição / Atualização e Baixa)' WHERE chave_questao = 'M07Q03531';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03540';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03550';
UPDATE questoes SET resposta_ref = '["Alvarás/licenças de funcionamento","Certidões","Licenças / autorizações","Ouvidoria","Consulta de débitos municipais","Emissão de guias/boletos dos débitos municipais","Inscrições em oficinas, cursos, eventos e vagas","Nota fiscal eletrônica","Canal de denúncias","Pesquisa de satisfação em relação aos serviços prestados pela Prefeitura","Consulta a status de protocolos de todos os atendimentos dos serviços assinalados acima"]' WHERE chave_questao = 'M07Q03610';
UPDATE questoes SET resposta_ref = '["Telefone","Site da Prefeitura","Redes sociais","Correio eletrônico (e-mail)"]' WHERE chave_questao = 'M07Q03710';
UPDATE questoes SET resposta_ref = 'Apenas regulamentou os Contratos terceirizados' WHERE chave_questao = 'M07Q03911R00100';
UPDATE questoes SET resposta_ref = 'A maior parte dos contratos vigentes' WHERE chave_questao = 'M07Q03920';
