-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Saude.JSON
-- Indicador: i-Saude

UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, com propostas para construção das diretrizes e metas da saúde municipal","valor":5},{"texto":"Sim, apenas aprovando as propostas da gestão (Secretaria Municipal)","valor":2},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q09900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Até prazo de envio à Câmara Municipal do projeto de lei sobre PPA 2022-2025","valor":10},{"texto":"Aprovado após prazo de envio à Câmara Municipal do projeto de lei sobre o PPA 2022-2025, mas antes da aprovação do PPA 2022-2025 pela Câmara Municipal","valor":7},{"texto":"Aprovado após a aprovação do PPA 2022-2025 pela Câmara Municipal","valor":3},{"texto":"Não aprovado","valor":0}]' WHERE chave_questao = 'M02Q06100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Até prazo de envio à Câmara Municipal do projeto de lei de diretrizes orçamentárias 2024","valor":10},{"texto":"Aprovado após prazo de envio à Câmara Municipal do projeto de lei de diretrizes orçamentárias 2024, mas antes da aprovação da LDO 2024 pela Câmara Municipal","valor":7},{"texto":"Aprovado após a aprovação da LDO 2024 pela Câmara Municipal","valor":3},{"texto":"Não aprovado","valor":0}]' WHERE chave_questao = 'M02Q06200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todas as ações foram executadas","valor":4},{"texto":"Sim, a maior parte das ações foram executadas","valor":2},{"texto":"Sim, a menor parte das ações foram executadas","valor":1},{"texto":"Nenhuma ação foi executada","valor":0}]' WHERE chave_questao = 'M02Q06210';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todas as metas foram atingidas","valor":4},{"texto":"Sim, a maior parte das metas foram atingidas","valor":2},{"texto":"Sim, a menor parte das metas foram atingidas","valor":1},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q06220';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Para outras secretarias / entidades municipais","valor":1},{"texto":"Não ofereceu nenhum curso/treinamento no ano","valor":0},{"texto":"Para escolas","valor":2.5},{"texto":"Para membros do Conselho Municipal de Saúde","valor":1},{"texto":"Para munícipes ou empresas","valor":1.5}]' WHERE chave_questao = 'M22Q10800';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q04100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q04110R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q04120R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q04130R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, com responsabilidade específica do setor de saúde e com recursos movimentados exclusivamente pelo Fundo","valor":5},{"texto":"Sim, com responsabilidade específica do setor de saúde, mas não houve movimentação de recursos exclusivamente pelo Fundo","valor":3},{"texto":"Sim, com recursos movimentados exclusivamente pelo Fundo, mas sem responsabilidade específica do setor de saúde","valor":1},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q05100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Relatório do 1º Quadrimestre até o final do mês de maio de 2024","valor":1},{"texto":"Relatório do 2º Quadrimestre até o final do mês de setembro de 2024","valor":1},{"texto":"Relatório do 3º Quadrimestre até o final do mês de fevereiro de 2025","valor":1},{"texto":"Não apresentou nenhum relatório quadrimestral dentro de prazo","valor":0},{"texto":"Não apresentou nenhum relatório quadrimestral em audiência pública na Câmara Municipal","valor":-1}]' WHERE chave_questao = 'M02Q06300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, meio eletrônico","valor":2},{"texto":"Sim, meio físico","valor":2},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q06400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06511R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Aprovado sem ressalvas","valor":18},{"texto":"Aprovado com ressalvas","valor":10},{"texto":"Irregular/Não aprovado","valor":0},{"texto":"Não apreciado","valor":-10}]' WHERE chave_questao = 'M02Q06500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R02800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R03000';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R02900';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R03200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06550R03100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q05800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q05821R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07111R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07111R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07120R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07120R00200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não houve registro eletrônico de nenhum profissional de saúde","valor":0}]' WHERE chave_questao = 'M02Q06700';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todos cumprem integralmente a jornada de trabalho","valor":15},{"texto":"Sim, a maior parte cumpre integralmente a jornada de trabalho","valor":8},{"texto":"Sim, todos permanecem apenas nas consultas agendadas","valor":5},{"texto":"Sim, a maior parte permanece apenas nas consultas agendadas","valor":2},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q06730';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Pronto atendimento","valor":1},{"texto":"Agendamento de cada paciente em horário único com, no mínimo, 15 minutos de atendimento","valor":1},{"texto":"Agendamento de cada paciente em horário único com menos de 15 minutos de atendimento","valor":0},{"texto":"Agendamento de 2 ou mais pacientes no mesmo horário","valor":0}]' WHERE chave_questao = 'M02Q06750';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q01800';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07210R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07210R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07210R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07220';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":0},{"texto":"Todos os exames laboratoriais são de pronto atendimento","valor":2}]' WHERE chave_questao = 'M02Q09700';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Atendimento pela ESF","valor":1},{"texto":"Consultas médicas em Atenção Primária","valor":1},{"texto":"Exames laboratoriais","valor":1},{"texto":"Terapias / tratamentos","valor":1},{"texto":"Medicamentos","valor":1},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q07310';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não, somente encaminhamento para outro município","valor":0}]' WHERE chave_questao = 'M02Q10900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Não houve registro eletrônico de nenhum profissional de saúde","valor":-3},{"texto":"Sim","valor":0}]' WHERE chave_questao = 'M02Q10901';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todos permanecem apenas nas consultas agendadas","valor":-4},{"texto":"Sim, todos cumprem integralmente a jornada de trabalho","valor":0},{"texto":"Não","valor":-5},{"texto":"Sim, a maior parte permanece apenas nas consultas agendadas","valor":-3},{"texto":"Sim, a maior parte cumpre integralmente a jornada de trabalho","valor":-1}]' WHERE chave_questao = 'M02Q10902';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, a maior parte dos médicos cumpre a jornada de trabalho","valor":-1},{"texto":"Não possui médicos plantonistas","valor":0},{"texto":"Não","valor":-5},{"texto":"Sim, a menor parte dos médicos cumprem a jornada de trabalho","valor":-3},{"texto":"Sim, todos cumprem integralmente a jornada de trabalho","valor":0}]' WHERE chave_questao = 'M02Q10903';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q10905';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q09883R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q09883R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q09883R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q10906';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q10908';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q10909R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q10909R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q10909R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q09884';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q10910';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M22Q10912';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Consultas por especialidade","valor":0},{"texto":"Exames","valor":0},{"texto":"Terapias / tratamentos","valor":0},{"texto":"Cirurgias eletivas","valor":0},{"texto":"OPM","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M22Q11000';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M22Q11600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"OPM","valor":0},{"texto":"Outros","valor":0},{"texto":"Cirurgias eletivas","valor":0},{"texto":"Medicamentos","valor":0},{"texto":"Terapias / tratamentos","valor":0},{"texto":"Exames radiológicos e por imagem","valor":0},{"texto":"Exames laboratoriais","valor":0},{"texto":"Consultas médicas por especialidade","valor":0}]' WHERE chave_questao = 'M22Q11700';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M22Q11800';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M22Q12000';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M22Q12100R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M22Q12200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07410';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07420';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07440';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07450';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07453';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07455';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07510';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07520R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07520R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07520R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07530';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q07540';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07550R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07550R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07550R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q07550R00400';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Imunobiológicos (soros, vacinas e imunoglobulinas)","valor":0},{"texto":"Meios de diagnóstico laboratorial para as doenças sob monitoramento epidemiológico (coleta de sangue, fluidos orgânicos como: saliva, secreção, suor, urina, fezes)","valor":0},{"texto":"Controle de vetores (inseticidas, larvicidas)","valor":0}]' WHERE chave_questao = 'M02Q09300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, em todos os estabelecimentos de saúde sob gestão municipal","valor":-5},{"texto":"Sim, na maior parte dos estabelecimentos de saúde sob gestão municipal","valor":-3},{"texto":"Sim, na menor parte dos estabelecimentos de saúde sob gestão municipal","valor":-1},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q09310';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, para todas as amostras","valor":0},{"texto":"Sim, para a maior parte das amostras","valor":-1},{"texto":"Sim, para a menor parte das amostras","valor":-3},{"texto":"Não","valor":-5}]' WHERE chave_questao = 'M02Q09320';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, para todos os profissionais","valor":0},{"texto":"Sim, para a maior parte dos profissionais","valor":-1},{"texto":"Sim, para a menor parte dos profissionais","valor":-3},{"texto":"Não","valor":-5}]' WHERE chave_questao = 'M02Q09330';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":10},{"texto":"Não","valor":0},{"texto":"Não houve casos de arboviroses","valor":10}]' WHERE chave_questao = 'M02Q07800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, investiga todos os casos","valor":30},{"texto":"Sim, investiga parte dos casos","valor":15},{"texto":"Não houve casos em 2024","valor":30},{"texto":"Não investiga","valor":0}]' WHERE chave_questao = 'M02Q07900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Incluir a vigilância sanitária municipal e como suporte às ações de vigilância e controle vetorial, que exigem o cumprimento da legislação sanitária","valor":3},{"texto":"Integrar as equipes de saúde da família nas atividades de controle vetorial, unificando os territórios de atuação de ACS e ACE","valor":3},{"texto":"Realizar o levantamento de indicadores entomológicos","valor":3},{"texto":"Executar as ações de controle mecânico, químico e biológico do mosquito","valor":3},{"texto":"Enviar os dados entomológicos ao nível estadual, dentro dos prazos estabelecidos","valor":3},{"texto":"Gerenciar os estoques municipais de inseticidas e biolarvicidas","valor":3},{"texto":"Adquirir as vestimentas e equipamentos necessários à rotina de controle vetorial","valor":3},{"texto":"Adquirir os equipamentos de EPI recomendados para a aplicação de inseticidas e biolarvicidas nas ações de rotina","valor":3},{"texto":"Coletar e enviar ao laboratório de referência amostras de sangue aos trabalhadores do controle vetorial que manuseiam inseticidas e/ou larvicidas, para dosagem de colinesterase, na frequência recomendada","valor":3},{"texto":"Possuir Comitê Gestor Intersetorial, sob coordenação da secretaria municipal de saúde, com representantes das áreas do município que tenham interface com o problema dengue (defesa civil, limpeza urbana, infraestrutura, segurança, turismo, planejamento, saneamento etc.), definindo responsabilidades, metas e indicadores de acompanhamento de cada área de atuação","valor":3},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q08010';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Planejamento familiar - concepção e contracepção (Prevenção à Gravidez)","valor":0.5},{"texto":"Pré-Natal","valor":0.5},{"texto":"Assistência ao parto, ao puerpério e ao neonato, incluindo aleitamento materno e doação de leite materno","valor":0.5},{"texto":"Prevenção às IST - Infecção Sexualmente Transmissível","valor":0.5},{"texto":"Prevenção dos cânceres do colo do útero, de mama e da saúde do homem","valor":0.5},{"texto":"Vacinação","valor":0.5},{"texto":"Doença Falciforme","valor":0},{"texto":"Hipertensão","valor":0.5},{"texto":"Diabetes","valor":0.5},{"texto":"Hanseníase","valor":0.5},{"texto":"Hepatite","valor":0.5},{"texto":"Coronavirus - COVID19","valor":0.5},{"texto":"Tuberculose","valor":0.5},{"texto":"Doença de Chagas","valor":0.5},{"texto":"Dengue/Zika/Chikungunya/Febre Amarela/Malária (Arboviroses)","valor":0.5},{"texto":"Tabaco","valor":0.5},{"texto":"Drogas e entorpecentes","valor":0.5},{"texto":"Saúde Bucal","valor":0.5},{"texto":"Doação de Sangue","valor":0.5},{"texto":"Doação de Órgãos","valor":0.5},{"texto":"Prevenção à Depressão e ao Suicídio","valor":0.5},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q08110';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q05700';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não possui controle da fila de espera","valor":0},{"texto":"Não possui fila de espera além da inserida no sistema de regulação do governo estadual","valor":5}]' WHERE chave_questao = 'M02Q10000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Em sistema informatizado","valor":5},{"texto":"De forma manual","valor":-5}]' WHERE chave_questao = 'M02Q10010';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"SIM, os cadastros de estabelecimentos e de profissionais estão atualizados","valor":15},{"texto":"Sim, somente o cadastro de estabelecimentos está atualizado","valor":5},{"texto":"Sim, somente o cadastro de profissionais está atualizado","valor":5},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M02Q08400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q05500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q05510';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Central de Urgência","valor":3},{"texto":"Central de Internações","valor":3},{"texto":"Central de Consultas e Serviços de Apoio Diagnóstico e terapêutico","valor":3}]' WHERE chave_questao = 'M02Q05511';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08610R00900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as equipes tinham composição mínima","valor":0},{"texto":"A maior parte das equipes tinham composição mínima","valor":-3},{"texto":"A menor parte das equipes tinham composição mínima","valor":-7},{"texto":"Nenhuma equipe tinha composição mínima","valor":-10}]' WHERE chave_questao = 'M02Q08620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as equipes tinham composição mínima","valor":0},{"texto":"A maior parte das equipes tinham composição mínima","valor":-10},{"texto":"A menor parte das equipes tinham composição mínima","valor":-15},{"texto":"Nenhuma equipe tinha composição mínima","valor":-20}]' WHERE chave_questao = 'M02Q08630';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Fornece a posição de estoque, movimentação de entrada e saída, lote e validade","valor":15},{"texto":"Gerenciar o processo de compras dos insumos/materiais de saúde, desde o planejamento até a entrega e o recebimento da nota fiscal","valor":15},{"texto":"Gerenciar a reposição dos insumos/materiais de saúde por estabelecimento de saúde","valor":15},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q00620';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q03900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Instituída por ato formal no organograma da secretaria de saúde ou equivalente","valor":3},{"texto":"Possui estrutura física","valor":2},{"texto":"Possui equipe ou profissional designado","valor":5},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q03930';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08700';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q00800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Instituído por ato formal no organograma da secretaria de saúde ou equivalente","valor":3},{"texto":"Possui estrutura física","valor":2},{"texto":"Possui equipe com ao menos um médico e um enfermeiro","valor":10},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q00810';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q00820';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q08800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Fornecer a posição de estoque, movimentação de entrada e saída, lote e validade","valor":10},{"texto":"Permitir a rastreabilidade dos medicamentos dispensados aos pacientes","valor":10},{"texto":"Gerenciar o processo de compras de itens de medicamentos, desde o planejamento até a entrega e o recebimento da nota fiscal","valor":10},{"texto":"Gerenciar a reposição de itens de medicamentos por estabelecimento de saúde","valor":10},{"texto":"Integrado à Base Nacional de Dados de Ações e Serviços da Assistência Farmacêutica (BNAFAR)","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M02Q08810';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08900R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q08900R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06000R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M02Q06000R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M02Q06600';
-- Respostas de referência Betim 2025 — i-Saude Nacional - 2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Sim, com propostas para construção das diretrizes e metas da saúde municipal' WHERE chave_questao = 'M02Q09900';
UPDATE questoes SET resposta_ref = 'Aprovado após a aprovação do PPA 2022-2025 pela Câmara Municipal' WHERE chave_questao = 'M02Q06100';
UPDATE questoes SET resposta_ref = 'Aprovado após a aprovação da LDO 2024 pela Câmara Municipal' WHERE chave_questao = 'M02Q06200';
UPDATE questoes SET resposta_ref = '["Para outras secretarias / entidades municipais","Para escolas","Para membros do Conselho Municipal de Saúde","Para munícipes ou empresas"]' WHERE chave_questao = 'M22Q10800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q04100';
UPDATE questoes SET resposta_ref = 'Sim, com responsabilidade específica do setor de saúde e com recursos movimentados exclusivamente pelo Fundo' WHERE chave_questao = 'M02Q05100';
UPDATE questoes SET resposta_ref = 'Não apresentou nenhum relatório quadrimestral em audiência pública na Câmara Municipal' WHERE chave_questao = 'M02Q06300';
UPDATE questoes SET resposta_ref = 'Sim, meio eletrônico' WHERE chave_questao = 'M02Q06400';
UPDATE questoes SET resposta_ref = 'Aprovado sem ressalvas' WHERE chave_questao = 'M02Q06500';
UPDATE questoes SET resposta_ref = '2' WHERE chave_questao = 'M02Q06550R02800';
UPDATE questoes SET resposta_ref = '81' WHERE chave_questao = 'M02Q06550R03000';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M02Q06550R02900';
UPDATE questoes SET resposta_ref = '80' WHERE chave_questao = 'M02Q06550R03200';
UPDATE questoes SET resposta_ref = '81' WHERE chave_questao = 'M02Q06550R00100';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q06550R03100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q05800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q06700';
UPDATE questoes SET resposta_ref = 'Agendamento de 2 ou mais pacientes no mesmo horário.' WHERE chave_questao = 'M02Q06750';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q01800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07200';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q09700';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07500';
UPDATE questoes SET resposta_ref = '["Imunobiológicos (soros, vacinas e imunoglobulinas)","Meios de diagnóstico laboratorial para as doenças sob monitoramento epidemiológico (coleta de sangue, fluidos orgânicos como: saliva, secreção, suor, urina, fezes)","Controle de vetores (inseticidas, larvicidas)"]' WHERE chave_questao = 'M02Q09300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07800';
UPDATE questoes SET resposta_ref = 'Sim, investiga todos os casos' WHERE chave_questao = 'M02Q07900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q05700';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10000';
UPDATE questoes SET resposta_ref = 'SIM, os cadastros de estabelecimentos e de profissionais estão atualizados' WHERE chave_questao = 'M02Q08400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q05500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q00600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q03900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08700';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q00800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q08800';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M02Q08900R00100';
UPDATE questoes SET resposta_ref = '298' WHERE chave_questao = 'M02Q08900R00200';
UPDATE questoes SET resposta_ref = '405 441 436,9200' WHERE chave_questao = 'M02Q06000R00100';
UPDATE questoes SET resposta_ref = '503 463 556,1200' WHERE chave_questao = 'M02Q06000R00200';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q06600';
UPDATE questoes SET resposta_ref = 'Sim, a maior parte das ações foram executadas' WHERE chave_questao = 'M02Q06210';
UPDATE questoes SET resposta_ref = 'Sim, a maior parte das metas foram atingidas' WHERE chave_questao = 'M02Q06220';
UPDATE questoes SET resposta_ref = 'Brasil e Caixa Econômica Federal.' WHERE chave_questao = 'M02Q04110R00100';
UPDATE questoes SET resposta_ref = '0750-1 е 0892, respectivamente.' WHERE chave_questao = 'M02Q04120R00100';
UPDATE questoes SET resposta_ref = '81.501-2 e 71.017-2, respectivamente.' WHERE chave_questao = 'M02Q04130R00100';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/- (secretarias, secretaria municipal de saúde) e https://digisusgmp.saude.gov.br/v1.5/transparencia' WHERE chave_questao = 'M02Q06511R00100';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/gestao-pessoas' WHERE chave_questao = 'M02Q05821R00100';
UPDATE questoes SET resposta_ref = '21' WHERE chave_questao = 'M02Q07111R00200';
UPDATE questoes SET resposta_ref = '92' WHERE chave_questao = 'M02Q07111R00100';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q07120R00300';
UPDATE questoes SET resposta_ref = '417153' WHERE chave_questao = 'M02Q07120R00200';
UPDATE questoes SET resposta_ref = 'Sim, todos cumprem integralmente a jornada de trabalho' WHERE chave_questao = 'M02Q06730';
UPDATE questoes SET resposta_ref = '5,0000' WHERE chave_questao = 'M02Q07210R00100';
UPDATE questoes SET resposta_ref = '0,0000' WHERE chave_questao = 'M02Q07210R00200';
UPDATE questoes SET resposta_ref = '8,5000' WHERE chave_questao = 'M02Q07210R00300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07220';
UPDATE questoes SET resposta_ref = '["Atendimento pela ESF","Consultas médicas em Atenção Primária","Exames laboratoriais","Terapias / tratamentos","Medicamentos","Outros"]' WHERE chave_questao = 'M02Q07310';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10901';
UPDATE questoes SET resposta_ref = 'Sim, a maior parte cumpre integralmente a jornada de trabalho' WHERE chave_questao = 'M02Q10902';
UPDATE questoes SET resposta_ref = 'Não possui médicos plantonistas' WHERE chave_questao = 'M02Q10903';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10905';
UPDATE questoes SET resposta_ref = '16,0000' WHERE chave_questao = 'M02Q09883R00100';
UPDATE questoes SET resposta_ref = '16,0000' WHERE chave_questao = 'M02Q09883R00200';
UPDATE questoes SET resposta_ref = '22,0000' WHERE chave_questao = 'M02Q09883R00300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10906';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10908';
UPDATE questoes SET resposta_ref = '37,0000' WHERE chave_questao = 'M02Q10909R00300';
UPDATE questoes SET resposta_ref = '20,0000' WHERE chave_questao = 'M02Q10909R00100';
UPDATE questoes SET resposta_ref = '41,0000' WHERE chave_questao = 'M02Q10909R00200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q09884';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q10910';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M22Q10912';
UPDATE questoes SET resposta_ref = '["Consultas por especialidade","Exames","Terapias / tratamentos","Cirurgias eletivas","OPM"]' WHERE chave_questao = 'M22Q11000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M22Q11600';
UPDATE questoes SET resposta_ref = '["Consultas médicas por especialidade"]' WHERE chave_questao = 'M22Q11700';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M22Q11800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M22Q12000';
UPDATE questoes SET resposta_ref = '12719' WHERE chave_questao = 'M22Q12100R00300';
UPDATE questoes SET resposta_ref = '10326' WHERE chave_questao = 'M22Q12100R00100';
UPDATE questoes SET resposta_ref = '13145' WHERE chave_questao = 'M22Q12100R00200';
UPDATE questoes SET resposta_ref = '6' WHERE chave_questao = 'M22Q12100R00600';
UPDATE questoes SET resposta_ref = '4' WHERE chave_questao = 'M22Q12100R00500';
UPDATE questoes SET resposta_ref = '4' WHERE chave_questao = 'M22Q12100R00400';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M22Q12200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07410';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07420';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07440';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07450';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q07453';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q07455';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q07510';
UPDATE questoes SET resposta_ref = '3' WHERE chave_questao = 'M02Q07520R00100';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q07520R00200';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q07520R00300';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q07530';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q07540';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q07550R00100';
UPDATE questoes SET resposta_ref = '0' WHERE chave_questao = 'M02Q07550R00200';
UPDATE questoes SET resposta_ref = '14' WHERE chave_questao = 'M02Q07550R00300';
UPDATE questoes SET resposta_ref = '14' WHERE chave_questao = 'M02Q07550R00400';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q09310';
UPDATE questoes SET resposta_ref = 'Sim, para todas as amostras' WHERE chave_questao = 'M02Q09320';
UPDATE questoes SET resposta_ref = 'Sim, para todos os profissionais' WHERE chave_questao = 'M02Q09330';
UPDATE questoes SET resposta_ref = '["Incluir a vigilância sanitária municipal e como suporte às ações de vigilância e controle vetorial, que exigem o cumprimento da legislação sanitária","Integrar as equipes de saúde da família nas atividades de controle vetorial, unificando os territórios de atuação de ACS e ACE","Realizar o levantamento de indicadores entomológicos","Executar as ações de controle mecânico, químico e biológico do mosquito","Enviar os dados entomológicos ao nível estadual, dentro dos prazos estabelecidos","Gerenciar os estoques municipais de inseticidas e biolarvicidas","Adquirir as vestimentas e equipamentos necessários à rotina de controle vetorial","Adquirir os equipamentos de EPI recomendados para a aplicação de inseticidas e biolarvicidas nas ações de rotina","Coletar e enviar ao laboratório de referência amostras de sangue aos trabalhadores do controle vetorial que manuseiam inseticidas e/ou larvicidas, para dosagem de colinesterase, na frequência recomendada","Possuir Comitê Gestor Intersetorial, sob coordenação da secretaria municipal de saúde, com representantes das áreas do município que tenham interface com o problema dengue (defesa civil, limpeza urbana, infraestrutura, segurança, turismo, planejamento, saneamento etc.), definindo responsabilidades, metas e indicadores de acompanhamento de cada área de atuação","Outros"]' WHERE chave_questao = 'M02Q08010';
UPDATE questoes SET resposta_ref = '["Planejamento familiar concepção e contracepção (Prevenção à Gravidez)","Pré-Natal","Assistência ao parto, ao puerpério e ao neonato, incluindo aleitamento materno e doação de leite materno","Prevenção às IST - Infecção Sexualmente Transmissível","Prevenção dos cânceres do colo do útero, de mama e da saúde do homem","Vacinação","Diabetes","Hanseníase","Hepatite","Tuberculose","Doença de Chagas","Tabaco","Doação de Sangue","Doação de Órgãos","Prevenção à Depressão e ao Suicídio","Outros"]' WHERE chave_questao = 'M02Q08110';
UPDATE questoes SET resposta_ref = 'Em sistema informatizado' WHERE chave_questao = 'M02Q10010';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M02Q05510';
UPDATE questoes SET resposta_ref = '["Central de Urgência","Central de Internações","Central de Consultas e Serviços de Apoio Diagnóstico e terapêutico"]' WHERE chave_questao = 'M02Q05511';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M02Q08610R00100';
UPDATE questoes SET resposta_ref = '16' WHERE chave_questao = 'M02Q08610R00200';
UPDATE questoes SET resposta_ref = '92' WHERE chave_questao = 'M02Q08610R00300';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M02Q08610R00400';
UPDATE questoes SET resposta_ref = '17' WHERE chave_questao = 'M02Q08610R00500';
UPDATE questoes SET resposta_ref = '108' WHERE chave_questao = 'M02Q08610R00600';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M02Q08610R00700';
UPDATE questoes SET resposta_ref = '17' WHERE chave_questao = 'M02Q08610R00800';
UPDATE questoes SET resposta_ref = '107' WHERE chave_questao = 'M02Q08610R00900';
UPDATE questoes SET resposta_ref = 'Todas as equipes tinham composição mínima' WHERE chave_questao = 'M02Q08620';
UPDATE questoes SET resposta_ref = 'Todas as equipes tinham composição mínima' WHERE chave_questao = 'M02Q08630';
UPDATE questoes SET resposta_ref = '["Fornece a posição de estoque, movimentação de entrada e saída, lote e validade","Gerenciar o processo de compras dos insumos/materiais de saúde, desde o planejamento até a entrega e o recebimento da nota fiscal","Gerenciar a reposição dos insumos/materiais de saúde por estabelecimento de saúde"]' WHERE chave_questao = 'M02Q00620';
UPDATE questoes SET resposta_ref = '["Instituída por ato formal no organograma da secretaria de saúde ou equivalente","Possui estrutura física","Possui equipe ou profissional designado"]' WHERE chave_questao = 'M02Q03930';
UPDATE questoes SET resposta_ref = '["Instituído por ato formal no organograma da secretaria de saúde ou equivalente","Possui estrutura física","Possui equipe com ao menos um médico e um enfermeiro"]' WHERE chave_questao = 'M02Q00810';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M02Q00820';
UPDATE questoes SET resposta_ref = '["Fornecer a posição de estoque, movimentação de entrada e saída, lote e validade","Permitir a rastreabilidade dos medicamentos dispensados aos pacientes","Gerenciar o processo de compras de itens de medicamentos, desde o planejamento até a entrega e o recebimento da nota fiscal","Gerenciar a reposição de itens de medicamentos por estabelecimento de saúde","Integrado à Base Nacional de Dados de Ações e Serviços da Assistência Farmacêutica (BNAFAR)"]' WHERE chave_questao = 'M02Q08810';
