-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Amb.json
-- Indicador: I-Amb Nacional - 2025

UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00910';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00912';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Para escolas","valor":5},{"texto":"Para munícipes ou empresas","valor":3},{"texto":"Para outras secretarias / entidades municipais","valor":2},{"texto":"Não ofereceu nenhum curso/treinamento no ano","valor":0}]' WHERE chave_questao = 'M05Q00942';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Recursos Tecnológicos","valor":5},{"texto":"Recursos Orçamentários","valor":5},{"texto":"Recursos Materiais","valor":5},{"texto":"Outros","valor":5}]' WHERE chave_questao = 'M05Q00940';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03350';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00500R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, para todos os órgãos e entidades","valor":10},{"texto":"Parcialmente","valor":3},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M05Q00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Coleta seletiva","valor":1.5},{"texto":"Uso racional da água","valor":1.5},{"texto":"Uso racional de energia elétrica","valor":1.5},{"texto":"Reúso de materiais","valor":1.5},{"texto":"Horta coletiva","valor":1.5},{"texto":"Compostagem","valor":1.5},{"texto":"Instalação de bicicletários e vestiários para os servidores públicos","valor":1.5},{"texto":"Implantação de caixas acopladas nos vasos sanitários","valor":1.5},{"texto":"Substituição de lâmpadas fluorescentes por lâmpadas LED","valor":1.5},{"texto":"Instalação de estruturas para a captação de água de chuva","valor":1.5},{"texto":"Instalação de torneiras com redutores de pressão","valor":1.5},{"texto":"Substituição de material descartável","valor":1.5},{"texto":"Logística reversa de pilhas, baterias e eletrônicos","valor":1.5},{"texto":"Outros","valor":0.5}]' WHERE chave_questao = 'M05Q00620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, com medição da densidade colorimétrica da Escala Ringelmann ou equivalente","valor":20},{"texto":"Sim, através de outra forma de medição","valor":15},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M05Q44100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03510R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Plano emergencial ou de contingenciamento sobre abastecimento de água no caso de sua escassez","valor":30},{"texto":"Manejo/manobras de água entre os reservatórios","valor":0},{"texto":"Campanha de conscientização da população","valor":5},{"texto":"Busca de fontes alternativas de abastecimento, como: poços artesianos","valor":0},{"texto":"Uso racional da distribuição de água (racionamento)","valor":0},{"texto":"Implantação de rodízio de fornecimento de água","valor":0},{"texto":"Redução da pressão no abastecimento de água","valor":0},{"texto":"Multa em caso de desperdício de água","valor":0},{"texto":"Tarifa/taxa diferenciada para o aumento de consumo de água","valor":0},{"texto":"Fornecimento de caminhões pipa","valor":0},{"texto":"Drenagem pluvial","valor":0},{"texto":"Incentivo à instalação de sistema para água de reúso","valor":5},{"texto":"Redução das perdas na distribuição de água","valor":0},{"texto":"Desassoreamento","valor":0},{"texto":"Divulgação dos resultados obtidos com o contingenciamento, situação dos mananciais/represas/ETAs","valor":10}]' WHERE chave_questao = 'M05Q01620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Rede Municipal de Educação","valor":10},{"texto":"Rede Municipal da Atenção Básica da Saúde","valor":10},{"texto":"Outro","valor":5}]' WHERE chave_questao = 'M05Q01950';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01111R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Metas de expansão do serviço de abastecimento de água","valor":0},{"texto":"Metas de redução de perdas na distribuição de água tratada","valor":2.5},{"texto":"Metas de qualidade na prestação do serviço de abastecimento de água","valor":2.5},{"texto":"Metas de eficiência e de uso racional da água","valor":2.5},{"texto":"Estabelecimento de volume mínimo de abastecimento de água per capita","valor":2.5},{"texto":"Estabelecimento de direitos e deveres dos usuários","valor":2.5},{"texto":"Meta de universalização do abastecimento de água potável até 31 de dezembro de 2033","valor":2.5},{"texto":"Estabelecimento de cronograma para o atingimento das metas assinaladas acima","valor":5}]' WHERE chave_questao = 'M05Q03620';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03610R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01121';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Metas de expansão do serviço de coleta de esgoto","valor":0},{"texto":"Metas de qualidade na prestação do serviço de coleta de esgoto","valor":3.5},{"texto":"Meta do reúso de efluentes sanitários","valor":3.5},{"texto":"Estabelecimento de direitos e deveres dos usuários","valor":3.5},{"texto":"Meta de universalização da coleta de esgoto até 31 de dezembro de 2033","valor":3.5},{"texto":"Estabelecimento de cronograma para o atingimento das metas assinaladas acima","valor":6}]' WHERE chave_questao = 'M05Q03630';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01124R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01125';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01128R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01129';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Relatórios anuais discutidos e/ou publicados","valor":0},{"texto":"Indicadores de eficácia e eficiência","valor":0},{"texto":"Avaliação de recursos aplicados","valor":0},{"texto":"Outro","valor":0}]' WHERE chave_questao = 'M05Q01130';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01120';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as metas foram cumpridas dentro do prazo","valor":50},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M05Q01132';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":3},{"texto":"Não","valor":0},{"texto":"Não há áreas prioritárias/críticas no município","valor":3}]' WHERE chave_questao = 'M05Q01140';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01150R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00111R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00150';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00140';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00250';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Diariamente","valor":0},{"texto":"3 vezes na semana","valor":0},{"texto":"2 vezes na semana","valor":0},{"texto":"1 vez na semana","valor":0},{"texto":"A cada 15 dias","valor":0},{"texto":"Mensalmente","valor":0}]' WHERE chave_questao = 'M05Q00253';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todos os bairros do município são atendidos","valor":100},{"texto":"A maior parte dos bairros são atendidos","valor":50},{"texto":"A menor parte dos bairros são atendidos","valor":10}]' WHERE chave_questao = 'M05Q00260';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00270';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Divulgações em redes sociais e/ou site da prefeitura","valor":1},{"texto":"Ações de educação ambiental","valor":0.5},{"texto":"Campanhas de conscientização por meio de sinalizações, folders, cartazes, propagandas e materiais impressos","valor":1},{"texto":"Projetos de incentivo","valor":1},{"texto":"Workshops/Palestras","valor":0.5},{"texto":"Instalação de lixeiras seletivas e distribuição de sacolas retornáveis para separação dos resíduos recicláveis","valor":1}]' WHERE chave_questao = 'M05Q00272';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03320';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todos os bairros do município são atendidos","valor":0},{"texto":"A maior parte dos bairros são atendidos","valor":-10},{"texto":"A menor parte dos bairros são atendidos","valor":-30}]' WHERE chave_questao = 'M05Q03330';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03340';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00331R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00360';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00363';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as metas foram cumpridas dentro do prazo","valor":40},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M05Q00366';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Falta de recursos orçamentários","valor":0},{"texto":"Falta de aprovação legislativa","valor":0},{"texto":"Atraso na licitação","valor":0},{"texto":"Não realizou licitação necessária","valor":0},{"texto":"Falta de pessoal qualificado","valor":0},{"texto":"Falta de consenso no consórcio intermunicipal","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M05Q00367';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Gerador dos resíduos","valor":0},{"texto":"Prefeitura","valor":-10},{"texto":"Outros","valor":-10}]' WHERE chave_questao = 'M05Q02500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00370';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q02650';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q02600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Local da instalação foi planejado","valor":0},{"texto":"Capacidade do local é definida","valor":0},{"texto":"Há desenvolvimento de células individuais","valor":0},{"texto":"Impermeabilização do solo","valor":0},{"texto":"Total gestão do chorume","valor":0},{"texto":"Total gestão dos gases","valor":0},{"texto":"Aplicação diária de camadas intermediárias e finais cobertura do solo","valor":0},{"texto":"Há compactação dos resíduos","valor":0},{"texto":"Há proteção vegetal (manutenção do paisagismo sobre as células de resíduos)","valor":0},{"texto":"Há desenvolvimento e manutenção das vias de acesso do aterro","valor":0},{"texto":"Há cercas/muros ao redor do local do aterro","valor":0},{"texto":"Há controle de acesso ao local do aterro","valor":0},{"texto":"Controle total do quantitativo de resíduos que entram no aterro","valor":0},{"texto":"Controle total da procedência dos resíduos que entram no aterro","valor":0},{"texto":"Controle total da composição dos resíduos que entram no aterro","valor":0},{"texto":"Não há coleta de resíduos por catadores dentro do aterro","valor":0},{"texto":"Não há comércio de resíduos dentro do aterro","valor":0},{"texto":"Não há presença de animais domésticos e/ou animais silvestres","valor":0},{"texto":"Não há odores nem presença de moscas","valor":0},{"texto":"Não há queima de resíduos dentro do aterro","valor":0},{"texto":"Conhecimento da data provável de fechamento do aterrо","valor":0},{"texto":"Previsão de gerenciamento do aterro pós-fechamento","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M05Q02670';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03700';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Campanhas de conscientização","valor":5},{"texto":"Mobilização de grupos de bairro","valor":5},{"texto":"Retirada dos resíduos sólidos por caminhões","valor":5},{"texto":"Sinalização no local sobre a proibição de descarte naquele local","valor":5},{"texto":"Plantio de árvores em áreas que não deveriam receber lixo ou entulho","valor":5},{"texto":"Notificações e multas aos responsáveis","valor":5}]' WHERE chave_questao = 'M05Q03730';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Abastecimento de água potável:","valor":1},{"texto":"Esgotamento sanitário:","valor":1},{"texto":"Limpeza urbana e manejo de resíduos sólidos:","valor":1},{"texto":"Drenagem e manejo das águas pluviais urbanas:","valor":0}]' WHERE chave_questao = 'M05Q03810';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03811R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03812R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q04000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Abastecimento de água e esgotamento sanitário","valor":0},{"texto":"Limpeza urbana e manejo de resíduos sólidos","valor":0},{"texto":"Drenagem e manejo de águas pluviais urbanas","valor":0}]' WHERE chave_questao = 'M05Q04010';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04012R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04012R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04013R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04013R00200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":0},{"texto":"Não foi informado ao SNIS","valor":0}]' WHERE chave_questao = 'M05Q04100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":5},{"texto":"Não","valor":0},{"texto":"Não foi informado ao SNIS","valor":0}]' WHERE chave_questao = 'M05Q04200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03200';
