-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Educ.JSON
-- Indicador: i-Educ

UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q13900';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06420R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12400R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12400R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12400R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12400R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06440';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06441';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Diária","valor":5},{"texto":"A cada 2 dias","valor":4},{"texto":"A cada 3 dias","valor":3},{"texto":"Semanal","valor":2},{"texto":"Mensal","valor":1},{"texto":"> 30 dias","valor":0}]' WHERE chave_questao = 'M01Q06442';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06443';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06450R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06450R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06450R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06450R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12500R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12500R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01300R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03700R00600';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06470';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06471R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06471R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06471R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06471R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06460R00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06460R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06460R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06460R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00220R00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não realiza reuniões periódicas","valor":0}]' WHERE chave_questao = 'M01Q06481';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"O kit escolar permanece no almoxarifado da escola e é retirado no momento do uso pelos alunos","valor":18},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M01Q06483';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06484R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":0},{"texto":"O material didático é elaborado na própria escola","valor":18}]' WHERE chave_questao = 'M01Q06485';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06486R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06487R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06487R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06489R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06489R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06489R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06489R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q14000';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06510R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13800R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13800R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13800R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13800R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06530';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06531';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Diária","valor":5},{"texto":"A cada 2 dias","valor":4},{"texto":"A cada 3 dias","valor":3},{"texto":"Semanal","valor":2},{"texto":"Mensal","valor":1},{"texto":"> 30 dias","valor":0}]' WHERE chave_questao = 'M01Q06532';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06533';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06540R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06540R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06540R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06540R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12800R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12800R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01305R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03705R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06570';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06571R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06571R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06571R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06571R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06560R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06560R00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06560R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06560R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00225R00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sobre planejamento e desempenho da criança","valor":2},{"texto":"Apenas sobre o projeto político-pedagógico","valor":1.5},{"texto":"Apenas sobre o desempenho da criança","valor":1},{"texto":"Não realiza reuniões periódicas","valor":0}]' WHERE chave_questao = 'M01Q06581';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"O kit escolar permanece no almoxarifado da escola e é retirado no momento do uso pelos alunos","valor":18},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M01Q06583';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06584R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":0},{"texto":"O material didático é elaborado na própria escola","valor":18}]' WHERE chave_questao = 'M01Q06585';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06586R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00305';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06587R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06587R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06589R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06589R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06589R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06589R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02800R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02800R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02800R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02800R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13200R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13200R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01306R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03706R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q07100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07110R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07110R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07110R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07110R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07000R00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07000R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07000R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07000R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00226R00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sobre planejamento e desempenho da criança","valor":2},{"texto":"Apenas sobre o projeto político-pedagógico","valor":1.5},{"texto":"Apenas sobre o desempenho da criança","valor":1},{"texto":"Não realiza reuniões periódicas","valor":0}]' WHERE chave_questao = 'M01Q07400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07200R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q02100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q07500';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"O kit escolar permanece no almoxarifado da escola e é retirado no momento do uso pelos alunos","valor":20},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M01Q07600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07610R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q07700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q07710R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q07800';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q07900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08200R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08200R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02900R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02900R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02700R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02700R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02700R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q02700R00400';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, utilizando contratação de terceiros","valor":1},{"texto":"Sim, utilizando metodologia desenvolvida exclusivamente pelos profissionais da rede","valor":2.5},{"texto":"Não utilizou","valor":0}]' WHERE chave_questao = 'M01Q06701';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03200R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q03310';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q03330';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as metas foram atingidas","valor":0},{"texto":"A maior parte das metas foram atingidas","valor":-5},{"texto":"A menor parte das metas foram atingidas","valor":-7},{"texto":"Nenhuma meta foi atingida","valor":-10}]' WHERE chave_questao = 'M01Q03311';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Ligação/mensagem para os responsáveis","valor":0},{"texto":"Visita domiciliar","valor":0},{"texto":"Plataforma de Busca Ativa (UNICEF)","valor":0},{"texto":"Contato com familiares/amigos/vizinhos","valor":0},{"texto":"Apoio do psicólogo escolar","valor":0},{"texto":"Apoio do orientador comunitário/assistente social escolar","valor":0},{"texto":"Encaminhamento do caso ao Conselho Tutelar","valor":0},{"texto":"Encaminhamento do caso ao CRAS - Centro de Referência de Assistência Social","valor":0},{"texto":"Outro","valor":0}]' WHERE chave_questao = 'M01Q00130';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00120R00400';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08700R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08700R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08700R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q08700R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13500R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q13500R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01307R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q03707R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q09200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09210R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09210R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09210R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09210R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09000R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09000R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09000R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09000R00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09100R00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sobre planejamento e desempenho da criança","valor":0},{"texto":"Apenas sobre o projeto político-pedagógico","valor":0},{"texto":"Apenas sobre o desempenho da criança","valor":0},{"texto":"Não realiza reuniões periódicas","valor":0}]' WHERE chave_questao = 'M01Q09500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09300R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q09600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"O kit escolar permanece no almoxarifado da escola e é retirado no momento do uso pelos alunos","valor":0},{"texto":"Não","valor":0}]' WHERE chave_questao = 'M01Q09700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09710R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q09800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q09810R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q09900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10000';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10010R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10020';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10021R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10030';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10040';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10041R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10041R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10400R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10400R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11100R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11100R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10700R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10700R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10700R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10700R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10800R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10900';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q10910R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q10920';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as metas foram atingidas","valor":0},{"texto":"A maior parte das metas foram atingidas","valor":0},{"texto":"A menor parte das metas foram atingidas","valor":0},{"texto":"Nenhuma meta foi atingida","valor":0}]' WHERE chave_questao = 'M01Q10921';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q11200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Ligação/mensagem para os responsáveis","valor":0},{"texto":"Visita domiciliar","valor":0},{"texto":"Plataforma de Busca Ativa (UNICEF)","valor":0},{"texto":"Contato com familiares/amigos/vizinhos","valor":0},{"texto":"Apoio do psicólogo escolar","valor":0},{"texto":"Apoio do orientador comunitário/assistente social escolar","valor":0},{"texto":"Encaminhamento do caso ao Conselho Tutelar","valor":0},{"texto":"Encaminhamento do caso ao CRAS Centro de Referência de Assistência Social","valor":0},{"texto":"Outro","valor":0}]' WHERE chave_questao = 'M01Q11210';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00600';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11220R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01000R00400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q01000R00500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q05300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q05320R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Remuneração condigna dos profissionais na educação básica da rede pública","valor":0},{"texto":"Integração entre o trabalho individual e a proposta pedagógica da escola","valor":0},{"texto":"Melhoria da qualidade do ensino e da aprendizagem","valor":0},{"texto":"Medidas de incentivo para que profissionais mais bem avaliados exerçam suas funções em escolas de locais com piores indicadores socioeconômicos ou que atendam estudantes com deficiência...","valor":0},{"texto":"Contempla capacitação profissional especialmente direcionada à formação continuada com vistas à melhoria da qualidade do ensino","valor":0},{"texto":"Nenhum dos anteriores","valor":0}]' WHERE chave_questao = 'M01Q11430';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q05200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q11400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11410R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q11410R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q11420';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Na Secretaria de Educação e em todas as escolas","valor":2},{"texto":"Na Secretaria de Educação e na maior parte das escolas","valor":1.3},{"texto":"Na Secretaria de Educação e na menor parte das escolas","valor":0.6},{"texto":"Apenas na Secretaria de Educação","valor":0},{"texto":"Não é divulgado","valor":0}]' WHERE chave_questao = 'M01Q11500';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Em todas as escolas","valor":2.5},{"texto":"Na maior parte das escolas","valor":1.8},{"texto":"Na menor parte das escolas","valor":0.5},{"texto":"Não cumpre o cardápio","valor":0}]' WHERE chave_questao = 'M01Q11600';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q11700';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Condições físicas e estruturais da cozinha","valor":0.25},{"texto":"Recebimento dos alimentos para controle de procedência","valor":0.25},{"texto":"Higienização dos alimentos","valor":0.25},{"texto":"Higienização dos equipamentos","valor":0.25},{"texto":"Acondicionamento dos alimentos","valor":0.25},{"texto":"Acompanhamento da preparação dos alimentos","valor":0.25},{"texto":"Acompanhamento e orientação sobre a manipulação dos alimentos","valor":0.25},{"texto":"Aceitação do cardápio proposto","valor":0.25},{"texto":"Outras","valor":0}]' WHERE chave_questao = 'M01Q11710';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q11800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Controle de Estoque com sistema PVPS","valor":0.38},{"texto":"Telas nas janelas e frestas","valor":0.35},{"texto":"Possui sistema de ventilação","valor":0.35},{"texto":"As luminárias são protegidas","valor":0.35},{"texto":"Possui ralos sifonados","valor":0.35},{"texto":"O estoque não possui sinais de goteiras, umidade...","valor":0.35},{"texto":"Há adequada distância no armazenamento de produtos","valor":0.35},{"texto":"As geladeiras/câmaras frias são higienizadas periodicamente","valor":0.35},{"texto":"Ventilação do estoque","valor":0.35},{"texto":"Temperatura","valor":0.35},{"texto":"Umidade do ar","valor":0.35},{"texto":"Prazo de validade","valor":0.35},{"texto":"Tipo de alimento","valor":0.35},{"texto":"Os alimentos abertos são etiquetados com data","valor":0.35},{"texto":"Desinsetização a cada 6 meses","valor":0.35},{"texto":"Desratização a cada 6 meses","valor":0.35},{"texto":"Limpeza da caixa dágua a cada 6 meses","valor":0.38},{"texto":"Outro","valor":0}]' WHERE chave_questao = 'M01Q11810';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q08100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q08111';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q08130';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q08140';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todos os veículos","valor":0},{"texto":"Sim, a maior parte dos veículos","valor":-2},{"texto":"Sim, a menor parte dos veículos","valor":-3},{"texto":"Não","valor":-5}]' WHERE chave_questao = 'M01Q13300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todos os condutores","valor":0},{"texto":"Sim, a maior parte dos condutores","valor":-2},{"texto":"Sim, a menor parte dos condutores","valor":-3},{"texto":"Não","valor":-5}]' WHERE chave_questao = 'M01Q14500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q14600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim, todos os condutores","valor":0},{"texto":"Sim, a maior parte dos condutores","valor":-1},{"texto":"Sim, a menor parte dos condutores","valor":-2},{"texto":"Não","valor":-3}]' WHERE chave_questao = 'M01Q14700';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00800';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q00811R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q00830';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Todas as metas foram atingidas dentro do prazo","valor":30},{"texto":"A maior parte das metas foram atingidas dentro do prazo","valor":17},{"texto":"A menor parte das metas foram atingidas dentro do prazo","valor":5},{"texto":"Nenhuma meta foi atingida no prazo","valor":0}]' WHERE chave_questao = 'M01Q00831';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12000';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Recursos Humanos","valor":0.5},{"texto":"Recursos Tecnológicos","valor":0.5},{"texto":"Estrutura Física","valor":0.5},{"texto":"Recursos Orçamentários","valor":0.5},{"texto":"Recursos Materiais","valor":0.5},{"texto":"Outros","valor":0.5}]' WHERE chave_questao = 'M01Q12110';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Consultiva","valor":0.5},{"texto":"Normativa","valor":0.5},{"texto":"Deliberativa","valor":0.5},{"texto":"Fiscalizadora","valor":0.5},{"texto":"Mobilizadora","valor":0.5},{"texto":"Propositiva","valor":0.5}]' WHERE chave_questao = 'M01Q14800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Consultas à sociedade sobre as necessidades e prioridades locais de educação","valor":0.6},{"texto":"Participação na discussão e definição das políticas e do planejamento educacional","valor":0.6},{"texto":"Acompanhamento e controle dos atos praticados pelos gestores da educação","valor":0.6},{"texto":"Elaboração de propostas para melhoria do fluxo escolar","valor":0.6},{"texto":"Elaboração de propostas para melhoria do rendimento escolar","valor":0.6},{"texto":"Sugestões de medidas para atualização e capacitação dos professores por meio da educação continuada","valor":0.6},{"texto":"Acompanhamento e avaliação do cumprimento do Plano Municipal de Educação","valor":0.6},{"texto":"Fiscalização da implementação do BNCC (Base Nacional Comum Curricular)","valor":0.6},{"texto":"Emissão de pareceres, resoluções, instruções e recomendações sobre a educação","valor":0.6},{"texto":"Aprovação dos regimentos escolares e suas alterações","valor":0.6},{"texto":"Apuração da existência de irregularidades na gerência dos recursos educacionais","valor":0},{"texto":"Outros","valor":0}]' WHERE chave_questao = 'M01Q14900';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":-50},{"texto":"Não compete ao Conselho aprovar as contas da Secretaria","valor":0}]' WHERE chave_questao = 'M01Q03400';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q05600R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q15100R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q15200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Nomes dos conselheiros e das entidades ou segmentos que representam;","valor":0.4},{"texto":"Correio eletrônico ou outro canal de contato direto com o conselho","valor":0.4},{"texto":"Atas de reuniões","valor":0.4},{"texto":"Relatórios e pareceres","valor":0.4},{"texto":"Outros documentos produzidos pelo conselho","valor":0.4}]' WHERE chave_questao = 'M01Q15210';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q15220R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Recursos Humanos","valor":0.5},{"texto":"Recursos Tecnológicos","valor":0.5},{"texto":"Estrutura Física","valor":0.5},{"texto":"Recursos Orçamentários","valor":0.5},{"texto":"Recursos Materiais","valor":0.5},{"texto":"Outros","valor":0.5}]' WHERE chave_questao = 'M01Q12210';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Elaboração do parecer das prestações de contas do FUNDEB","valor":1.5},{"texto":"Supervisão da elaboração da proposta orçamentária anual","valor":0.5},{"texto":"Apresentação de manifestação formal acerca dos registros contábeis e demonstrativos gerenciais do Fundo aos órgãos competentes","valor":0.5},{"texto":"Convocação dos responsáveis para prestação de esclarecimentos acerca do fluxo de recursos e da execução das despesas do Fundo","valor":0.5},{"texto":"Requisição ao Poder Executivo de cópia de documentos","valor":0.5},{"texto":"Visitas para verificações in loco","valor":1},{"texto":"Supervisão do censo escolar anual","valor":1},{"texto":"Acompanhar a aplicação dos recursos federais transferidos à conta do PNATE e do PEJA e analisar suas prestações de contas","valor":0.5}]' WHERE chave_questao = 'M01Q15300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Aprovado sem ressalva","valor":0},{"texto":"Aprovado com ressalva","valor":0},{"texto":"Não aprovado","valor":-50},{"texto":"Não apreciado","valor":-20}]' WHERE chave_questao = 'M01Q12220';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q12230R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12300';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Recursos Humanos","valor":0.5},{"texto":"Recursos Tecnológicos","valor":0.5},{"texto":"Estrutura Física","valor":0.5},{"texto":"Recursos Orçamentários","valor":0.5},{"texto":"Recursos Materiais","valor":0.5},{"texto":"Outros","valor":0.5}]' WHERE chave_questao = 'M01Q12310';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12320';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q12330';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Acompanhamento e fiscalização do cumprimento das diretrizes estabelecidas sobre alimentação escolar","valor":0.5},{"texto":"Acompanhamento e fiscalização da aplicação dos recursos destinados à alimentação escolar","valor":1},{"texto":"Aferição da qualidade dos alimentos, em especial quanto às condições higiênicas, bem como a aceitabilidade dos cardápios oferecidos","valor":1},{"texto":"Aferição das condições físicas e estruturais da cozinha","valor":1},{"texto":"Sobre o relatório anual de gestão do PNAE, emitiu parecer conclusivo a respeito, aprovando ou reprovando a execução do Programa","valor":1},{"texto":"Comunicou aos órgãos de controle as irregularidades observadas","valor":0},{"texto":"Forneceu informações e apresentou relatórios de acompanhamento da execução do PNAE sempre que solicitado","valor":0},{"texto":"Realizou visitas periódicas às escolas","valor":1},{"texto":"Realizou reuniões periódicas","valor":0.5}]' WHERE chave_questao = 'M01Q15400';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '[{"texto":"Sim","valor":0},{"texto":"Não","valor":0},{"texto":"Houve adesão ao Currículo elaborado pela Secretaria da Educação do Estado?","valor":0}]' WHERE chave_questao = 'M01Q13700';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06000R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06100R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06200R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M01Q06200R00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M01Q06300';
