-- Atualização de tipos e opções gerada por importar-opcoes-gemini.js
-- Fonte: scripts/i-Amb.json
-- Indicador: I-Amb Nacional - 2025

UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00900';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00910';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00911R00300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00912';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Para escolas","Para munícipes ou empresas","Para outras secretarias / entidades municipais","Não ofereceu nenhum curso/treinamento no ano"]' WHERE chave_questao = 'M05Q00942';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Recursos Tecnológicos","Recursos Orçamentários","Recursos Materiais","Outros"]' WHERE chave_questao = 'M05Q00940';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03350';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00500R00100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Sim, para todos os órgãos e entidades","Parcialmente","Não"]' WHERE chave_questao = 'M05Q00600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Coleta seletiva","Uso racional da água","Uso racional de energia elétrica","Reúso de materiais","Horta coletiva","Compostagem","Instalação de bicicletários e vestiários para os servidores públicos","Implantação de caixas acopladas nos vasos sanitários","Substituição de lâmpadas fluorescentes por lâmpadas LED","Instalação de estruturas para a captação de água de chuva","Instalação de torneiras com redutores de pressão","Substituição de material descartável","Logística reversa de pilhas, baterias e eletrônicos","Outros"]' WHERE chave_questao = 'M05Q00620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Sim, com medição da densidade colorimétrica da Escala Ringelmann ou equivalente","Sim, através de outra forma de medição","Não"]' WHERE chave_questao = 'M05Q44100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03500';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03510R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Plano emergencial ou de contingenciamento sobre abastecimento de água no caso de sua escassez","Manejo/manobras de água entre os reservatórios","Campanha de conscientização da população","Busca de fontes alternativas de abastecimento, como: poços artesianos","Uso racional da distribuição de água (racionamento)","Implantação de rodízio de fornecimento de água","Redução da pressão no abastecimento de água","Multa em caso de desperdício de água","Tarifa/taxa diferenciada para o aumento de consumo de água","Fornecimento de caminhões pipa","Drenagem pluvial","Incentivo à instalação de sistema para água de reúso","Redução das perdas na distribuição de água","Desassoreamento","Divulgação dos resultados obtidos com o contingenciamento, situação dos mananciais/represas/ETAs"]' WHERE chave_questao = 'M05Q01620';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Rede Municipal de Educação","Rede Municipal da Atenção Básica da Saúde","Outro"]' WHERE chave_questao = 'M05Q01950';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01111R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Metas de expansão do serviço de abastecimento de água","Metas de redução de perdas na distribuição de água tratada","Metas de qualidade na prestação do serviço de abastecimento de água","Metas de eficiência e de uso racional da água","Estabelecimento de volume mínimo de abastecimento de água per capita","Estabelecimento de direitos e deveres dos usuários","Meta de universalização do abastecimento de água potável até 31 de dezembro de 2033","Estabelecimento de cronograma para o atingimento das metas assinaladas acima"]' WHERE chave_questao = 'M05Q03620';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03610R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01121';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Metas de expansão do serviço de coleta de esgoto","Metas de qualidade na prestação do serviço de coleta de esgoto","Meta do reúso de efluentes sanitários","Estabelecimento de direitos e deveres dos usuários","Meta de universalização da coleta de esgoto até 31 de dezembro de 2033","Estabelecimento de cronograma para o atingimento das metas assinaladas acima"]' WHERE chave_questao = 'M05Q03630';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01124R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01125';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01128R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01129';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Relatórios anuais discutidos e/ou publicados","Indicadores de eficácia e eficiência","Avaliação de recursos aplicados","Outro"]' WHERE chave_questao = 'M05Q01130';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q01120';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Todas as metas foram cumpridas dentro do prazo","Não"]' WHERE chave_questao = 'M05Q01132';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Sim","Não","Não há áreas prioritárias/críticas no município"]' WHERE chave_questao = 'M05Q01140';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q01150R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00111R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00150';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00140';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00250';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Diariamente","3 vezes na semana","2 vezes na semana","1 vez na semana","A cada 15 dias","Mensalmente"]' WHERE chave_questao = 'M05Q00253';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Todos os bairros do município são atendidos","A maior parte dos bairros são atendidos","A menor parte dos bairros são atendidos"]' WHERE chave_questao = 'M05Q00260';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00270';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Divulgações em redes sociais e/ou site da prefeitura","Ações de educação ambiental","Campanhas de conscientização por meio de sinalizações, folders, cartazes, propagandas e materiais impressos","Projetos de incentivo","Workshops/Palestras","Instalação de lixeiras seletivas e distribuição de sacolas retornáveis para separação dos resíduos recicláveis"]' WHERE chave_questao = 'M05Q00272';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03300';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03320';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Todos os bairros do município são atendidos","A maior parte dos bairros são atendidos","A menor parte dos bairros são atendidos"]' WHERE chave_questao = 'M05Q03330';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03340';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00300';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q00331R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00360';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00363';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Todas as metas foram cumpridas dentro do prazo","Não"]' WHERE chave_questao = 'M05Q00366';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Falta de recursos orçamentários","Falta de aprovação legislativa","Atraso na licitação","Não realizou licitação necessária","Falta de pessoal qualificado","Falta de consenso no consórcio intermunicipal","Outros"]' WHERE chave_questao = 'M05Q00367';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Gerador dos resíduos","Prefeitura","Outros"]' WHERE chave_questao = 'M05Q02500';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q00370';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q02650';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q02600';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Local da instalação foi planejado","Capacidade do local é definida","Há desenvolvimento de células individuais","Impermeabilização do solo","Total gestão do chorume","Total gestão dos gases","Aplicação diária de camadas intermediárias e finais cobertura do solo","Há compactação dos resíduos","Há proteção vegetal (manutenção do paisagismo sobre as células de resíduos)","Há desenvolvimento e manutenção das vias de acesso do aterro","Há cercas/muros ao redor do local do aterro","Há controle de acesso ao local do aterro","Controle total do quantitativo de resíduos que entram no aterro","Controle total da procedência dos resíduos que entram no aterro","Controle total da composição dos resíduos que entram no aterro","Não há coleta de resíduos por catadores dentro do aterro","Não há comércio de resíduos dentro do aterro","Não há presença de animais domésticos e/ou animais silvestres","Não há odores nem presença de moscas","Não há queima de resíduos dentro do aterro","Conhecimento da data provável de fechamento do aterrо","Previsão de gerenciamento do aterro pós-fechamento","Outros"]' WHERE chave_questao = 'M05Q02670';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03700';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Campanhas de conscientização","Mobilização de grupos de bairro","Retirada dos resíduos sólidos por caminhões","Sinalização no local sobre a proibição de descarte naquele local","Plantio de árvores em áreas que não deveriam receber lixo ou entulho","Notificações e multas aos responsáveis"]' WHERE chave_questao = 'M05Q03730';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03800';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Abastecimento de água potável:","Esgotamento sanitário:","Limpeza urbana e manejo de resíduos sólidos:","Drenagem e manejo das águas pluviais urbanas:"]' WHERE chave_questao = 'M05Q03810';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03811R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q03812R00100';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q04000';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Abastecimento de água e esgotamento sanitário","Limpeza urbana e manejo de resíduos sólidos","Drenagem e manejo de águas pluviais urbanas"]' WHERE chave_questao = 'M05Q04010';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04012R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04012R00200';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04013R00100';
UPDATE questoes SET tipo = 'text', opcoes = NULL WHERE chave_questao = 'M05Q04013R00200';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Sim","Não","Não foi informado ao SNIS"]' WHERE chave_questao = 'M05Q04100';
UPDATE questoes SET tipo = 'multipla_escolha', opcoes = '["Sim","Não","Não foi informado ao SNIS"]' WHERE chave_questao = 'M05Q04200';
UPDATE questoes SET tipo = 'boolean', opcoes = NULL WHERE chave_questao = 'M05Q03200';
