-- Respostas de referência Betim 2025 — i-Plan TCEMG-2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q01400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03700';
UPDATE questoes SET resposta_ref = '["Dispor sobre pagamento de servidor ou empregado público com recursos vinculados à parceria firmada com o terceiro setor","Critérios para ajuda financeira a entidades da Administração indireta","Critérios para repasses a entidades do terceiro setor","Custos estimados, indicadores e metas físicas que se correlacionam com as ações do governo municipal","Critérios para o Poder Executivo estabelecer a programação financeira mensal para todo o Município, nele incluído a Câmara","Percentual da Receita Corrente Líquida que será retido, na peça orçamentária, enquanto Reserva de Contingência, destinada a passivos contingentes e outros riscos fiscais","Critérios para limitação de empenho e movimentação financeira; ressalvados os pagamentos do serviço da dívida, os relativos à inovação e ao desenvolvimento científico e tecnológico custeadas por fundo criado para tal finalidade.","Critérios para contratação de horas extras quando o Poder superar o limite prudencial para pessoal: Executivo, 51,30% da RCL; Legislativo, 5,7% da RCL","Autorização para o Município auxiliar o custeio de despesas próprias do Estado e da União"]' WHERE chave_questao = 'M03Q04010';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q02100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04200';
UPDATE questoes SET resposta_ref = '["As receitas e despesas da LOA são compatíveis com o Resultado Primário da LDO, incluindo, no máximo, a variação da inflação do interregno temporal dos referidos projetos de lei","O Resultado Nominal constante da LDO consta da LOA, com variação de no máximo a variação da inflação do interregno temporal dos referidos projetos de lei","A estimativa de renúncia fiscal prevista na LDO coincide com o estimado na LOA com variação limitada à variação da inflação","A estimativa de receita e respectivos critérios presentes na LOA são compatíveis com os previstos na LDO em relação à receita de IPTU","A estimativa de receita e respectivos critérios presentes na LOA são compatíveis com os previstos na LDO em relação à receita de ISSQN","A estimativa de receita e respectivos critérios presentes na LOA são compatíveis com os previstos na LDO em relação à receita de ITBI","Os investimentos, parte das despesas de capital, previstas na LOA e LDO são compatíveis com as previsões do PPA","Programas constantes do PPA constam na LOA","Programas e ações constantes da LDO constam da LOA"]' WHERE chave_questao = 'M03Q04310';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q02000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q00700';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q02500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04400';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q04500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q01000';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03400';
UPDATE questoes SET resposta_ref = '["LDO 2024","PPA inicial 2022-2025","LOA 2024"]' WHERE chave_questao = 'M03Q01890';
UPDATE questoes SET resposta_ref = '["Dia de semana em horário comercial (8 as 18 horas)"]' WHERE chave_questao = 'M03Q01850';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q01810';
UPDATE questoes SET resposta_ref = '["Planejamento logístico. Ex.: localização do ambiente, acomodações adequadas aos participantes, regulação e testagem dos equipamentos eletrônicos (som, vídeo e iluminação), verificação dos equipamentos relacionados a transmissão das audiências etc.","Estabelecimento da abordagem de interação","Estabelecimento da Pauta","Indicação de mediador qualificado"]' WHERE chave_questao = 'M03Q01812';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q01430';
UPDATE questoes SET resposta_ref = 'Sim, para a maior parte dos programas do PPA' WHERE chave_questao = 'M03Q13800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03910';
UPDATE questoes SET resposta_ref = 'Não houve avaliação' WHERE chave_questao = 'M03Q03911';
UPDATE questoes SET resposta_ref = 'A menor parte dos indicadores' WHERE chave_questao = 'M03Q03920';
UPDATE questoes SET resposta_ref = '["Plano Diretor","Plano Municipal da Educação","Plano Municipal da Saúde","Plano de Mobilidade Urbana","Plano de Saneamento Básico","Plano de Resíduos Sólidos","Plano de Contingência Municipal - PLANCON de Defesa Civil"]' WHERE chave_questao = 'M03Q03930';
UPDATE questoes SET resposta_ref = '["Imposto sobre a Propriedade Predial e Territorial Urbano (IPTU)","Transferências Obrigatórias Recebidas do Estado. Ex.: ICMS, IPVA.","Outros","Transferências Obrigatórias Recebidas da União. Ex.: FPM, CIDE, ITR, Royalties e FUNDEB.","Contribuições","Taxas","Imposto Sobre Serviços de Qualquer Natureza (ISSQN)","Imposto sobre a Transmissão de Bens Imóveis (ITBI)"]' WHERE chave_questao = 'M03Q03710';
UPDATE questoes SET resposta_ref = 'Sim, com reestimativa da receita prevista na LOA no decorrer da execução orçamentária-financeira' WHERE chave_questao = 'M03Q03712';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03730';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/orcamento' WHERE chave_questao = 'M03Q04130R00100';
UPDATE questoes SET resposta_ref = '["Metas Fiscais Atuais Comparadas com as Metas Fiscais Fixadas nos três exercícios anteriores","Margem de Expansão das Despesas Obrigatórias de Caráter Continuado","Origem e Aplicação dos Recursos Obtidos com a Alienação de Ativos","Avaliação da Situação Financeira e Atuarial do RPPS","Estimativa e Compensação da Renúncia de Receita","Outros","Metas Anuais","Avaliação do Cumprimento das Metas Fiscais do Exercício Anterior","Evolução do Patrimônio Líquido"]' WHERE chave_questao = 'M03Q04121';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/orcamento' WHERE chave_questao = 'M03Q04230R00100';
UPDATE questoes SET resposta_ref = '["Estimativa do grau de tolerância das contas públicas ao comportamento frente ao risco"]' WHERE chave_questao = 'M03Q04221';
UPDATE questoes SET resposta_ref = '30,0000' WHERE chave_questao = 'M03Q02010R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q00710';
UPDATE questoes SET resposta_ref = 'Sim, todos os servidores possuem qualificação técnica' WHERE chave_questao = 'M03Q00711';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q00900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q02550';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M23Q02592';
UPDATE questoes SET resposta_ref = 'https://servicos.betim.mg.gov.br/transparencia/#/metas-fiscais' WHERE chave_questao = 'M23Q02593R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q02590';
UPDATE questoes SET resposta_ref = 'Sim, com emissão de relatórios e ciência do prefeito' WHERE chave_questao = 'M03Q02540';
UPDATE questoes SET resposta_ref = 'https://sistemas.betim.mg.gov.br/controladoria/' WHERE chave_questao = 'M03Q03021R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03060';
UPDATE questoes SET resposta_ref = '["Comprovar a legalidade dos repasses a entidades do terceiro setor, avaliando a eficácia e a eficiência dos resultados alcançados","Exercer o controle das operações de crédito, avais e garantias, bem como dos direitos e haveres do Município","Em conjunto com autoridades da Administração Financeira do Município, assinar o Relatório de Gestão Fiscal","Atestar a regularidade da tomada de contas dos ordenadores de despesa, recebedores, tesoureiros, pagadores ou assemelhados","Apoiar o Tribunal de Contas no exercício de sua missão institucional","Constatar se está sendo satisfeito o limite para gastos totais das Câmaras Municipais","Verificar a fidelidade funcional dos responsáveis por bens e valores públicos"]' WHERE chave_questao = 'M03Q03061';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03070';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03077';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03071';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04350';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03073';
UPDATE questoes SET resposta_ref = 'Gabinete do Prefeito' WHERE chave_questao = 'M03Q03082';
UPDATE questoes SET resposta_ref = 'Não houve irregularidades nem ilegalidades' WHERE chave_questao = 'M03Q03084';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03075';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M03Q03090';
UPDATE questoes SET resposta_ref = 'https://legislativo.camarabetim.mg.gov.br/NormaJuridica/ShowNormaJuridica/31959 https://legislativo.camarabetim.mg.gov.br/NormaJuridica/ShowNormaJuridica/37747' WHERE chave_questao = 'M03Q03321R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q03370';
UPDATE questoes SET resposta_ref = '["Número de manifestações recebidas no exercício anterior","Análise dos Pontos recorrentes"]' WHERE chave_questao = 'M03Q03371';
UPDATE questoes SET resposta_ref = 'https://sistemas.betim.mg.gov.br/acessoouvidoria/arquivo/dados_estatisticos_2024.pdf' WHERE chave_questao = 'M03Q03373R00100';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/portal/carta-servicos' WHERE chave_questao = 'M03Q04413R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04414';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M03Q04420';
UPDATE questoes SET resposta_ref = '11/03/2024' WHERE chave_questao = 'M03Q01040R00100';
