-- Respostas de referência Betim 2025 — I-Amb Nacional - 2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00900';
UPDATE questoes SET resposta_ref = 'Sim, para todos os órgãos e entidades' WHERE chave_questao = 'M05Q00600';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q44100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00300';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q02650';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q02600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03700';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03800';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q04000';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q04100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q04200';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q03200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00910';
UPDATE questoes SET resposta_ref = '26' WHERE chave_questao = 'M05Q00911R00100';
UPDATE questoes SET resposta_ref = '27' WHERE chave_questao = 'M05Q00911R00200';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M05Q00911R00300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00912';
UPDATE questoes SET resposta_ref = '["Para escolas","Para outras secretarias / entidades municipais"]' WHERE chave_questao = 'M05Q00942';
UPDATE questoes SET resposta_ref = '["Recursos Tecnológicos","Recursos Orçamentários","Recursos Materiais"]' WHERE chave_questao = 'M05Q00940';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03350';
UPDATE questoes SET resposta_ref = '69' WHERE chave_questao = 'M05Q00500R00100';
UPDATE questoes SET resposta_ref = '["Coleta seletiva","Uso racional da água","Uso racional de energia elétrica","Reúso de materiais","Compostagem","Instalação de bicicletários e vestiários para os servidores públicos","Substituição de lâmpadas fluorescentes por lâmpadas LED","Instalação de estruturas para a captação de água de chuva","Instalação de torneiras com redutores de pressão","Logística reversa de pilhas, baterias e eletrônicos","Substituição de material descartável"]' WHERE chave_questao = 'M05Q00620';
UPDATE questoes SET resposta_ref = 'ECO 003/2024 - SV EMPREENDIMENTOS IMOBILIÁRIOS LTDA' WHERE chave_questao = 'M05Q03510R00100';
UPDATE questoes SET resposta_ref = '["Plano emergencial ou de contingenciamento sobre abastecimento de água no caso de sua escassez"]' WHERE chave_questao = 'M05Q01620';
UPDATE questoes SET resposta_ref = '["Rede Municipal de Educação","Rede Municipal da Atenção Básica da Saúde"]' WHERE chave_questao = 'M05Q01950';
UPDATE questoes SET resposta_ref = 'www.dpurb.betim.mg.gov.br' WHERE chave_questao = 'M05Q01111R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03600';
UPDATE questoes SET resposta_ref = '["Meta de universalização do abastecimento de água potável até 31 de dezembro de 2033"]' WHERE chave_questao = 'M05Q03620';
UPDATE questoes SET resposta_ref = '31/12/2033' WHERE chave_questao = 'M05Q03610R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01121';
UPDATE questoes SET resposta_ref = '["Metas de expansão do serviço de coleta de esgoto","Metas de qualidade na prestação do serviço de coleta de esgoto","Estabelecimento de direitos e deveres dos usuários","Meta de universalização da coleta de esgoto até 31 de dezembro de 2033"]' WHERE chave_questao = 'M05Q03630';
UPDATE questoes SET resposta_ref = '31/12/2033' WHERE chave_questao = 'M05Q01124R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01125';
UPDATE questoes SET resposta_ref = '31/12/2033' WHERE chave_questao = 'M05Q01128R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01129';
UPDATE questoes SET resposta_ref = '["Relatórios anuais discutidos e/ou publicados"]' WHERE chave_questao = 'M05Q01130';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01120';
UPDATE questoes SET resposta_ref = 'Todas as metas foram cumpridas dentro do prazo' WHERE chave_questao = 'M05Q01132';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q01140';
UPDATE questoes SET resposta_ref = '30/09/2018' WHERE chave_questao = 'M05Q01150R00100';
UPDATE questoes SET resposta_ref = 'XYZ' WHERE chave_questao = 'M05Q00111R00100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q00150';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q00140';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00250';
UPDATE questoes SET resposta_ref = '3 vezes na semana' WHERE chave_questao = 'M05Q00253';
UPDATE questoes SET resposta_ref = 'A maior parte dos bairros são atendidos' WHERE chave_questao = 'M05Q00260';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00270';
UPDATE questoes SET resposta_ref = '["Ações de educação ambiental"]' WHERE chave_questao = 'M05Q00272';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q03320';
UPDATE questoes SET resposta_ref = 'Todos os bairros do município são atendidos' WHERE chave_questao = 'M05Q03330';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q03340';
UPDATE questoes SET resposta_ref = 'www.dpurb.betim.mg.gov.br' WHERE chave_questao = 'M05Q00331R00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00360';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q00363';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M05Q00366';
UPDATE questoes SET resposta_ref = '["Falta de recursos orçamentários"]' WHERE chave_questao = 'M05Q00367';
UPDATE questoes SET resposta_ref = 'Gerador dos resíduos' WHERE chave_questao = 'M05Q02500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M05Q00370';
UPDATE questoes SET resposta_ref = '["Local da instalação foi planejado","Capacidade do local é definida","Impermeabilização do solo","Total gestão do chorume","Total gestão dos gases","Aplicação diária de camadas intermediárias e finais - cobertura do solo","Há compactação dos resíduos","Há proteção vegetal (manutenção do paisagismo sobre as células de resíduos)","Há desenvolvimento e manutenção das vias de acesso do aterro","Há cercas/muros ao redor do local do aterro","Há controle de acesso ao local do aterro","Controle total do quantitativo de resíduos que entram no aterro","Controle total da procedência dos resíduos que entram no aterro","Não há coleta de resíduos por catadores dentro do aterro","Não há comércio de resíduos dentro do aterro","Não há presença de animais domésticos e/ou animais silvestres (urubus, garças, etc.)","Não há queima de resíduos dentro do aterro","Previsão de gerenciamento do aterro pós-fechamento"]' WHERE chave_questao = 'M05Q02670';
UPDATE questoes SET resposta_ref = '["Campanhas de conscientização","Retirada dos resíduos sólidos por caminhões","Sinalização no local sobre a proibição de descarte naquele local","Plantio de árvores em áreas que não deveriam receber lixo ou entulho"]' WHERE chave_questao = 'M05Q03730';
UPDATE questoes SET resposta_ref = '["Abastecimento de água potável:","Esgotamento sanitário:"]' WHERE chave_questao = 'M05Q03810';
UPDATE questoes SET resposta_ref = 'ECOS/DAΟΙΕ' WHERE chave_questao = 'M05Q03811R00100';
UPDATE questoes SET resposta_ref = 'ECOS/DAΟΙΕ' WHERE chave_questao = 'M05Q03812R00100';
UPDATE questoes SET resposta_ref = '["Limpeza urbana e manejo de resíduos sólidos"]' WHERE chave_questao = 'M05Q04010';
UPDATE questoes SET resposta_ref = '100' WHERE chave_questao = 'M05Q04012R00100';
UPDATE questoes SET resposta_ref = '100' WHERE chave_questao = 'M05Q04012R00200';
UPDATE questoes SET resposta_ref = '0.68' WHERE chave_questao = 'M05Q04013R00100';
UPDATE questoes SET resposta_ref = '0.9' WHERE chave_questao = 'M05Q04013R00200';
