-- Respostas de referência Betim 2025 — i-Gov Nacional - 2025
-- Gerado por importar-respostas-gemini.cjs

UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03300';
UPDATE questoes SET resposta_ref = 'SIM' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q01900';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02300';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03500';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03600';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03900';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q04100';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03000';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00300';
UPDATE questoes SET resposta_ref = '41' WHERE chave_questao = 'M07Q00310R00100';
UPDATE questoes SET resposta_ref = '4' WHERE chave_questao = 'M07Q00310R00200';
UPDATE questoes SET resposta_ref = '21' WHERE chave_questao = 'M07Q00310R00300';
UPDATE questoes SET resposta_ref = '1' WHERE chave_questao = 'M07Q00310R00400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00400';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00500';
UPDATE questoes SET resposta_ref = '["Infraestrutura e Redes","Desenvolvimento e Software","Análise de Dados","Gestão e Segurança"]' WHERE chave_questao = 'M07Q00520';
UPDATE questoes SET resposta_ref = 'Há participação do pessoal de TI no processo de compra (especificação técnica, comissão de julgamento, recebimento do objeto)' WHERE chave_questao = 'M07Q01000';
UPDATE questoes SET resposta_ref = '["Elaboração do edital / especificação técnica","Comissão de julgamento","Recebimento do objeto"]' WHERE chave_questao = 'M07Q01010';
UPDATE questoes SET resposta_ref = 'Sim, para a maior parte dos softwares' WHERE chave_questao = 'M07Q01020';
UPDATE questoes SET resposta_ref = 'SIM, com metas acima de 02 anos' WHERE chave_questao = 'M07Q00100';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00200';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q00220';
UPDATE questoes SET resposta_ref = 'Assinatura eletrônica onerosa' WHERE chave_questao = 'M07Q00222';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03442';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03410';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03420';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q03430';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q03440';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/arquivos/atos_21_20170529_284.pdf' WHERE chave_questao = 'M07Q01911R00100';
UPDATE questoes SET resposta_ref = 'https://www.betim.mg.gov.br/' WHERE chave_questao = 'M07Q00610R00100';
UPDATE questoes SET resposta_ref = 'Sim, para todo o conteúdo do site' WHERE chave_questao = 'M07Q00620';
UPDATE questoes SET resposta_ref = 'Possibilita para a maior parte dos relatórios' WHERE chave_questao = 'M07Q00630';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q00650';
UPDATE questoes SET resposta_ref = 'Sim, para todo o conteúdo do site' WHERE chave_questao = 'M07Q00660';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02310';
UPDATE questoes SET resposta_ref = 'Sim' WHERE chave_questao = 'M07Q02320';
UPDATE questoes SET resposta_ref = 'Não' WHERE chave_questao = 'M07Q02330';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Gestão de negócios (Business Intelligence)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03510';
UPDATE questoes SET resposta_ref = '["Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03530';
UPDATE questoes SET resposta_ref = 'Totalmente integrado (Inscrição / Atualização e Baixa)' WHERE chave_questao = 'M07Q03531';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03540';
UPDATE questoes SET resposta_ref = '["Contabilidade","Gestão de tributos (arrecadação)","Dívida Ativa","Precatórios","Gestão patrimonial (bens e equipamentos)","Planejamento","Recursos humanos / Departamento pessoal","Almoxarifado","Controle de frotas","Controle Interno","Saúde","Ensino (educação)","Compras, licitações e contratos","Certidões e alvarás","Saneamento","Cemitérios"]' WHERE chave_questao = 'M07Q03550';
UPDATE questoes SET resposta_ref = '["Alvarás/licenças de funcionamento","Certidões","Licenças / autorizações","Ouvidoria","Consulta de débitos municipais","Emissão de guias/boletos dos débitos municipais","Inscrições em oficinas, cursos, eventos e vagas","Nota fiscal eletrônica","Canal de denúncias","Pesquisa de satisfação em relação aos serviços prestados pela Prefeitura","Consulta a status de protocolos de todos os atendimentos dos serviços assinalados acima"]' WHERE chave_questao = 'M07Q03610';
UPDATE questoes SET resposta_ref = '["Telefone","Site da Prefeitura","Redes sociais","Correio eletrônico (e-mail)"]' WHERE chave_questao = 'M07Q03710';
UPDATE questoes SET resposta_ref = 'Apenas regulamentou os Contratos terceirizados' WHERE chave_questao = 'M07Q03911R00100';
UPDATE questoes SET resposta_ref = 'A maior parte dos contratos vigentes' WHERE chave_questao = 'M07Q03920';
